### ISSUE TITLE
PC Requirements

### ISSUE THREAD

**Issue by michaelhany55** [ApolloAuto/apollo#10045]
I was using a PC with with GTX 980ti GPU and of course it's too old and does not support many modules (including perception module of course). I want to use Apollo 3.5 or 5.0 with LGSVL simulator. I managed to build and run both of them and test the routing as mentioned in the installation guide of LGSVL.

Now I was looking to buy the recommended PC requirements which include the GTX 1080 GPU. This GPU stopped being produced. Therefore, my question is what other GPU could I buy that is also supported by Apollo.

I read in other issues that people are having trouble building apollo using RTX 2070 - 2080.

Any help would be appreciated.

### System information
- OS Platform and Distribution: Linux Ubuntu 18.04

Thanks

**Comment by Autofoxsys** [comment]
I have just tried to run Apollo with an Nvidia GTX **1050** GPU with **2GB**.
It does **not pass** the GPU tests (about 17 failures out of 558 tests in total).  For the vast majority of the failures (perhaps even all of them) it would seem to be due to insufficient GPU memory.

`bash apollo.sh test_gpu` (test run from within docker container).

I hoped that I could get away with that low spec card to at least test if my SW setup worked before purchasing a more expensive card.

**Comment by Autofoxsys** [comment]
After adding another GTX 1050Ti with **4GB** to the system I passed a few more tests but 6 are still failing due to memory allocation.

**Comment by cplusplus-is-best** [comment]
too much tests run at the same time. just add"exclusive" tag to (bazel)  the failed gpu test.

**Comment by Kailiangdong** [comment]
I have same question. Does the RTX2080 can build apollo now?

**Comment by faysalhossain2007** [comment]
Does Apollo support RTX now?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
