### ISSUE TITLE
Need updated Document to understand communication between modules after migration to CyberRT

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#10664]
Hello, 
I was trying to understand how the various modules in Apollo communicate with one another - I found this document[( https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_understand_architecture_and_workflow.md)], but this talks about how the communication relied on ROS1.

Can you kindly suggest a more updated document which talks about the same topic, after Apollo migrated to Cyber RT?

Thanks in advance.

**Comment by ntutangyun** [comment]
I'm also new, but as far as I know, Cyber RT modules communicate messages via shared memory. 
Thus saving cost on copying data around. 

It's like
module A -> publish message -> serialize message -> save to shared memory -> Module B reads from shared momory -> deserialize message. 

please correct me if I'm wrong. Thanks.

**Comment by quning18** [comment]
We do have some examples and documents to help you start coding on cyber RT.

For internal design, cyber RT support intra-process with no serialization cost, interprocess based on shared memory and intra-node based on RTPS. The basic idea is similiar to what we have done on Apollo ROS, but the performance has been improved a lot since then.

**Comment by Avps1** [comment]
Thanks for your response.
