### ISSUE TITLE
about cyber scheduler code

### ISSUE THREAD

**Issue by yiyibst** [ApolloAuto/apollo#10771]
[看了关于cyber调度的源码，发现在编排模式下（1）choreography_processor_num创建的个数过多，下面配置的时候用不到，会造成资源开销的浪费。不知道我理解的对不对。]
（2）pool_processor_num里创建的线程个数，其实没有起作用。因为放到pool里的task，都绑定到了一个线程中去。那么我的问题是:a)那pool_processor_num存在的意义是什么？b)是不是越少创建线程，越能节约资源？

**Comment by daohu527** [comment]
Cyber's schedule model is similar to **golang's GPM model**. To take full advantage of CPU efficiency, it is recommended that **the number of processors equals the number of CPU cores**.   

1. If you have a 20-core CPU, it should be reasonable to set 8 choreography_processor_num. Coroutine tasks will be added to the processor's local queue and then executed.  

2. Cyber will create a croutine pool which have pool_processor_num processors. You can add tasks larger than pool_processor_num to the coroutine pool, and they will be executed on different processors. Processors will fetch tasks from the global queue and execute them.

3. If you have more IO operations than calculation operations, you definitely need to create more threads because you can sleep and let other threads execute while the threads are waiting for IO.
With coroutines, you may not need to create so many threads. Creating threads slightly larger than the number of cores is actually sufficient.
