### ISSUE TITLE
Apollo not lane changing to destination lane

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10955]
Hi team,

**VIDEO**
https://drive.google.com/file/d/13TmSAzcbELp2cVleYN03M82BMCBhR00Z/view?usp=sharing

**Describe the bug**

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. I discovered some issues, which I think might relate to Apollo's routing, planning and control modules.

In the video, Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction inbetween.

The vehicle is spawned **near the first point of the starting lane**, and the routing destination is set **near the last point of the end lane**.

All the videos are recorded without any obstacle.
Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

**To Reproduce**

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo to take over.

**Expected behavior**
In this case, Apollo is expected to do a **left lane change after the junction**, however, it did not even try to do the lane change the whole time after passing the junction… 
Note that the destination point is set at the end of the left lane after the junction.

**Desktop (please complete the following information):**

OS: Ubuntu 1804
Browser Chrome

**Comment by daohu527** [comment]
Could you pls get some log about planning module, **some times the hd-map may have some error** like the two lanes gap is a little large, then the planning module will not able to turn to the neighbor lane.  

The apollo default lane width is 3.75m. I meet some case if the lane width is large than 3.75m, but apollo will calc with default value 3.75. Then there is a gap.  

I'm not sure this's the same problem.

**Comment by ntutangyun** [comment]
Here are the logs for the run, I've formatted in JSON...

https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/ETnUXW13oYNOl-Ib0lwOTNYBWGy9dDX0OPrQ8hXVnw_VXg?e=9HX57c

> The apollo default lane width is 3.75m. I meet some case if the lane width is large than 3.75m, but apollo will calc with default value 3.75. Then there is a gap.
I see. It might be the problem.  I will confirm on the lane width later.

**Comment by ntutangyun** [comment]
@daohu527 Hi, there are lots of similar cases in the San Francisco Map provided by LGSVL team. May I ask where can I increase this default lane width, and if this config is increased to say 5 meters, what will the side effects be ?

Thanks.

**Comment by daohu527** [comment]
Actually, apollo obtains the width of the road based on the information in the map, you can refer to
"apollo\modules\map\data\demo\base_map.txt".  

## apollo hd map lane info
If you got the San Francisco Map which is a bin file, you can use the tool in protobuf to unzip it to a txt file, then you can check the file si right or not.   

You can get 3 line in one lane, there are
```
left_boundary  central_curve  right_boundary
```
I also notice there is an width info in it, the role of simple information is still unclear to me, maybe the refence line ?
```
  left_sample {
    s: 153.87421245705966
    width: 1.7500000000000586
  }
  right_sample {
    s: 0
    width: 1.7499999999999967
  }
```

## problem

**Apollo gets road information based on the hd map, in fact you can run Apollo on any width lane**. The problem is the lgsvl provided hd map. They generate the map with default width 3.75, they don't draw the left and right boundary but just the central lane. And cacl the left and right boundary by 3.75m. So I think there is some work to deal with this problem.  

https://github.com/lgsvl/simulator/blob/4e852200c4ca559b22c50c87cdd7d25ba30cb374/Assets/Scripts/Editor/ApolloMapTool.cs#L543-L546

You can find the width in the lgsvl code, but changing the width will cause a road error of 1.75m(3.5m width, I was wrong before a 3.75). In addition, the sanfacso map will not be maintained in the new lgsvl version, it is recommended that you modify the map generation method. Like
```
If road id == xxx then
    width = 5
```
