### ISSUE TITLE
How to Update Vehicle Calibration for Throttle and Brakes? 

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#11090]
Question:
Q#1. In step 3-Plot results. how do we know the data is correct?
Q#2 what dose it mean (Adjust the command script based on the vehicle response) in collect data?
Q#3 In calibration table for one value of speed(0.0) there are many different cmd and acc, So how the control module knows which value (calibration) is to be used?

![Screenshot from 2020-04-22 10-37-03](https://user-images.githubusercontent.com/61130487/79934499-43b9fa80-8485-11ea-89c5-5d63733f026e.png)
![Screenshot from 2020-04-22 10-38-17](https://user-images.githubusercontent.com/61130487/79934561-66e4aa00-8485-11ea-966a-d5d366d64ba7.png)

Q#4. after doing all the process, I get (control_conf.pb.txt) but when i use that file for Auto Driving, the car dose not move. I think it is the Vehicle Calibration issue because when i use Apollo default (control_conf.pb.txt), then the car can move Auto but the control of steer , brake and throttle is not good, so i need to Update Vehicle Calibration.

Q#5. how to update calibration table for MPC_Controller, because after doing this the MPC_Controller calibration is same as before.

I read the file how_to_update_vehicle_calibration.md 
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_update_vehicle_calibration.md 
 It has 4 steps.
1- Collect data.
2- Process data.
3- Plot results.
4- Convert results to `protobuf`.

### Collect Data

 1. Run `python data_collector.py` for different commands, commands like x y z, where x is acceleration command, y is speed limit(mps), z is decceleration command,Positive number for throttle and negative number for brake.Run each command multiple times.
 2. Adjust the command script based on the vehicle response.
 3. Run `python plot_data.py ` to open recorded data and visualize collected data.

like `15 5.2 -10`, will create and record a file named `t15b-10r0.csv`.

### Process Data
Run `process_data.sh` on each recorded log individually. data log is processed to `t15b-10r0.csv.result`.

### Plot Results
Run `python plot_results.py t15b-10r0.csv.result` to visualize final results. Check for any abnormality.

### Convert Results to `Protobuf`
If everything looks good, run `result2pb.sh` to move calibration results to `protobuf` defined for the control module.

**Comment by tanmoy-sabir** [comment]
hello.  Did you get the answers to your questions?

Question:
Q#1. In step 3-Plot results. how do we know the data is correct?
Q#2 what does it mean (Adjust the command script based on the vehicle response) to collect data?
Q#3 In the calibration table for one value of speed(0.0) there are many different cmd and acc, So how the control module knows which value (calibration) is to be used?
Q#4. after doing all the process, I get (control_conf.pb.txt) but when I use that file for Auto Driving, the car does not move. I think it is the Vehicle Calibration issue because when I use Apollo default (control_conf.pb.txt), then the car can move Auto but the control of steer, brake and throttle is not good, so I need to Update Vehicle Calibration.
Q#5. how to update the calibration table for MPC_Controller, because after doing this the MPC_Controller calibration is the same as before.
