### ISSUE TITLE
Apollo trapped in deadlock with an obstacle inside junction

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11136]
Hi team,

***VIDEO:*** (WARNING: The video contains audio)
https://drive.google.com/file/d/1P_JUqhTEYDXntZ3DUgy3gtfSrieR9aFR/view?usp=sharing

***Describe the bug***

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. 

In the video, the Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction in-between.

The vehicle is spawned near the first point of the starting lane, and the routing destination is set near the last point of the end lane.

The obstacle is spawned in another place, goes straight when passing the junction, whose path intersects with Apollo's.

Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

***To Reproduce***

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo take over.

***Expected behavior***
To simulate the uncommon cases, I've configured all the traffic lights to green all the time. 

Thus from Apollo's point of view, it has the right of way. However, since Apollo is turning left and the obstacle is going straight, we believe the obstacle actually has the priority higher than Apollo. Thus Apollo should be brake early to not block the obstacle's way, instead of getting trapped in a deadlock of obstacle avoidance by both vehicles.

Also, I'd like to ask if Apollo is going to resolve such deadlocks by itself in future releases?

Thanks.

Desktop (please complete the following information):

OS: Ubuntu 1804
Browser Chrome

**Comment by jmtao** [comment]
@ntutangyun this is as expected.  
Because of the complexity of traffic condition inside junctions and safety concern, currently we are supporting "side-pass" obstacles inside junctions.  If we are unable to proceed safely within the lane boundaries, we'll just stop. 
We do support "side-pass" along normal driving lanes.

**Comment by ntutangyun** [comment]
@jmtao I see. thanks for your reply. 

However, below are two points of my concerns:
* I think it's still considered unsafe to just stop in the junction and blocking the traffic. 
* since Apollo is turning left and the obstacle is going straight, I believe obstacle has the right of way and thus Apollo should give way to the obstacle, by not stopping in the obstacle's straight going lane.  I mean, if Apollo stops on the position about 0:06 seconds, the obstacle should be able to continue. 

What do you think ?

**Comment by jmtao** [comment]
@ntutangyun sorry I missed a "not" in my previous post.  "we are NOT supporting 'side-pass" obstacles inside junctions". 
The problem is, at 0.06s, the predicted trajectory of that obstacle is too short to indicate it's gonna cross line with ADC. When it shows up at 0.07s, the fence is already at in front of ADC and there's no way for ADC to stop right there. 
improving prediction is a long term goal.

**Comment by ntutangyun** [comment]
@jmtao Absolutely. Although I just started, I've been realizing the difficulties ahead. Thanks for the reply. Closing the issue now.
