### ISSUE TITLE
Controller Tuning ofline is possible? 

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#11342]
Is it possible to do controller (PID or LQR or MPC) tuning offline using  record bag and Apollo dream view? 
If possible then how to do it?

**Comment by sjiang2018** [comment]
Hello, there! The short answer to this question is "yes, it's possible".
1. Filter out the control channel using cyber (https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md).
2. Play the filtered record  with cyber_recorder and you may monitor it with dream view.
3. Start control module on dream view front-end. Now you are using the controller with the parameters of your local Apollo repo.
4. Use cyber_monitor or dream view front-end to monitor the controller performance.
You might not be able to observe the behavior change of ego vehicle on dream view, because the localization info is recorded in the bag. But you can observe the control output changes when parameters are changed.

**Comment by Addi2020** [comment]
Thank you for response.
I did it the same way you explained . I can use the recorded file for control tuning and add log to debug lateral error, heading error, speed error, then try to minimize these error by tuning control parameters. Then apply it on real car and it works..
