### ISSUE TITLE
[PREDICTION] a typo maybe ?

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11381]
Hi,

I found the following mismatch in the Prediction source code. I don't fully understand the code yet. but please help check anyway :)

```c++
// modlues/prediction/common/message_process.cc:  line 62
  
 if (!FLAGS_use_navigation_mode && !PredictionMap::Ready()) {
    AERROR << "Map cannot be loaded.";
    return false;
  }

// modules/prediction/prediction_component.cc: line 185

  // Update relative map if needed
  if (FLAGS_use_navigation_mode && !PredictionMap::Ready()) {
    AERROR << "Relative map is empty.";
    return false;
  }
```
there is a not "!" before the `FLAGS_use_navigation_mode` in the first snippet, not in the second.

**Comment by kechxu** [comment]
Hi ntutangyun,

Thank you for your question. I think there is no typo. In the case of modlues/prediction/common/message_process.cc:  line 62, we check if map is ready in the initial status while we are NOT in navigation mode. But in navigation mode, we check if map is ready in every frame run instead of initial status.

**Comment by ntutangyun** [comment]
@kechxu alright. thanks for your reply.
