### ISSUE TITLE
The car can not follow the planning trajectory or navigation path? how to solve it?

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#11450]
The car can not follow the navigation path. what can be the problem?
I try to solve it by tuning MPC controller but not succeed. It is due to planning input or control steady state error.
the picture shows the car position and planing path.
![Screenshot from 2020-06-12 15-01-23](https://user-images.githubusercontent.com/61130487/84474772-02dca600-acbe-11ea-838b-114f3845264d.png)

**Comment by yifeijiang** [comment]
Can you provide more details for the setups? Is this case for running Apollo on a real vehicle? Apollo version? Using default planning algorithm? Did you try the default control algorithm instead of MPC one?  

Can you also provide more details for the issue itself? E.g., How did the vehicle behave when it "can not follow the navigation path"?

**Comment by Addi2020** [comment]
Apollo 3.5.0
Real Car
default planning
I used default control, try to tune LQR control for steer control but not find the parameter that is use to control steer, Then I use MPC control.
The issue was path following, the car moves in a zigzag motion, cant be stable on straight line but,
After tuning MPC control lateral error and heading error is minimized then the trajectory or path following problem is solved.
