### ISSUE TITLE
how can I debug a Dreamview demo in vscode?

### ISSUE THREAD

**Issue by rimu123** [ApolloAuto/apollo#11499]
I can run a Dreamview demo <demo_3.5.record>, but I can't enable SimControl, so I can't find the planning process.how can I debug a Dreamview demo in vscode?

**Comment by vlin17** [comment]
What do you mean you can't enable SimControl? Any error messages shown? 
In addition, playing back demo record doesn't need to enable SimControl or planning module. May we know what you are trying to achieve?

**Comment by rimu123** [comment]
reference to [https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md](url)
I want to debug a demo remotely using vscode. According to the above link, I need to find the planning process in the process list, which is the binary file I need to debug. But I cannot find him. So I doubt if I cannot enable SimControl, like this:
![404972697998510432](https://user-images.githubusercontent.com/33481776/85089006-04552380-b214-11ea-8b98-9622d99abf0d.jpg)

**Comment by machar94** [comment]
Sim Control might be enabled if you try shifting Lock Task Panel to the other side?

**Comment by rimu123** [comment]
It does not respond. I want to know whether it must be running on the hardware platform to debug, or any demo would do？

**Comment by vlin17** [comment]
Hi @rimu123  

1. SimControl is part of the Dreamview feature that simulates a SDC's control module, and moves the car based on planning result. This is a convenient way to visualize and test planning module. However, since this is part of the Dreamview feature, turning on sim control won't help finding planning process. 

2. As explained in the [document](https://github.com/ApolloAuto/apollo/blob/d669dd84e626e97e45efca8b73dd0caeb8423cc1/docs/howto/how_to_build_and_debug_using_vscode.md) you pointed out, to find the planning process id, we need to toggle the "Planning" option from "Module Controller". Only after the planning module is on, you will be able to find its process.
![Screen Shot 2020-06-22 at 1 12 09 PM](https://user-images.githubusercontent.com/2775888/85330859-fc061e00-b489-11ea-9464-63f70d04e7a4.png)

3. The document is about debugging planning module which publishes planning/control/etc data in realtime; while playing the 3.5 demo bag publishes recored planning/control data in the demo bag. You might not want to do both at the same time.

**Comment by Avps1** [comment]
> Hi @rimu123
> 
>     1. SimControl is part of the Dreamview feature that simulates a SDC's control module, and moves the car based on planning result. This is a convenient way to visualize and test planning module. However, since this is part of the Dreamview feature, turning on sim control won't help finding planning process.
> 
>     2. As explained in the [document](https://github.com/ApolloAuto/apollo/blob/d669dd84e626e97e45efca8b73dd0caeb8423cc1/docs/howto/how_to_build_and_debug_using_vscode.md) you pointed out, to find the planning process id, we need to toggle the "Planning" option from "Module Controller". Only after the planning module is on, you will be able to find its process.
>        ![Screen Shot 2020-06-22 at 1 12 09 PM](https://user-images.githubusercontent.com/2775888/85330859-fc061e00-b489-11ea-9464-63f70d04e7a4.png)
> 
>     3. The document is about debugging planning module which publishes planning/control/etc data in realtime; while playing the 3.5 demo bag publishes recored planning/control data in the demo bag. You might not want to do both at the same time.
Hi vlin17,
Did you try the VSCode debugging method that was mentioned in this doc to debug the PLANNING module?
I did and I ran into the following error : https://youtu.be/d9vcRATc3M0(Youtube video) and opened the following issue : 
https://github.com/ApolloAuto/apollo/issues/11107.
I would like to know if you are facing a similiar problem ?

**Comment by rimu123** [comment]
The control button can break the point, while the other buttons can not be paused, because I have an error when running, so I can not determine whether it can not break the point.
