### ISSUE TITLE
Routing moudle apply for A star

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#11798]
在Navigator::SearchRouteByStrategy这个函数中，对所有路径点做循环后应用A star算法
for (size_t i = 1; i < way_nodes.size(); ++i)；
其中way_nodes表示request请求中所有路径点，那么在这个循环之中应用A star算法，表示只在两个node之间应用A star算法吗？

如下的start、end代表相连接的两个node?
const auto* start = sub_graph.GetSubNodeWithS(way_start, way_start_s);
const auto* end = sub_graph.GetSubNodeWithS(way_end, way_end_s);

**Comment by daohu527** [comment]
**Your understanding is right**. "start" is the starting point, "end" is the destination. 

The normal case there's only one start point and end point. You can also set a bypass point so that you have multiple points to pass through. The bypass points are set by "RoutingRequest".
```
A(start) -> B -> C -> D (end)
```
The "way_nodes" is set by below code.   
https://github.com/ApolloAuto/apollo/blob/25c63a183b4736c04a8f00c04954f6e9aeafee5b/modules/routing/core/navigator.cc#L57-L70

**Comment by ManXiaoMi** [comment]
Thank you very much! I've got it.
