### ISSUE TITLE
How to start the perception module in Dreamview?

### ISSUE THREAD

**Issue by wuzp986** [ApolloAuto/apollo#12039]
Open the Camera, Velodyne, and Percetion modules on the ModuleController page, but Radar cannot be opened, and there is no message output on the cyber_channel echo obstacles topic in the terminal. How to correctly enable the Percetion function in Dreamview?

**Comment by jinghaomiao** [comment]
Toggle on velodyne and radar sensors in module controller, and make sure they have the correct outputs in the appropriate channels. And then toggle on perception in module controller. You have to choose a map before doing so. Thansk for using Apollo.

**Comment by wuzp986** [comment]
1. Open the "Sim Control" button in Figure 1;
2. Open the Camera, Velodyne, Perception options in Figure 2;
3. Why does Radar turn off automatically after opening?
4. How to start the perception module in offline simulation mode through the Dreamview interface?
![Dreamview1](https://user-images.githubusercontent.com/57422562/89498411-c9717400-d7f0-11ea-9829-0230f9380d91.png)
![dreamview2](https://user-images.githubusercontent.com/57422562/89498427-d0988200-d7f0-11ea-8103-fffa9d8e70e9.png)

**Comment by jinghaomiao** [comment]
1) Sim Control only works in offline playback mode. It won't be useful for onboard road test
3) Without connecting to radar device, the module will not be able to turn on as it checks the hardware. So it won't work in offline playback mode
4) You need to play a data record with raw sensor data (lidar and radar) and then turn on perception in offline playback mode so that perception module would work. (camera won't work in current master branch as of now and team is working on a fix)

Hope your questions are answered. Thanks for using Apollo.

**Comment by wuzp986** [comment]
Thank you！
