### ISSUE TITLE
Protobuf with bazel

### ISSUE THREAD

**Issue by liukr001** [ApolloAuto/apollo#12069]
I download the Protobuf repo to my local computer, 
and in the workspace how do I configure it to compile with Bazel.
Workspace has the following contents
 local_repository(
    name = "com_google_protobuf",
    path = "/home/ws/protobuf-3.12.3/",
  )
What else do I need to configure.Thanks

**Comment by liukr001** [comment]
and what causes this problem   
 //main:t1.out
    //main:t1_lib
    //proto:t1_cc_proto
    //proto:t1_proto
.-> @com_google_protobuf//:protoc (host)
|   @com_google_protobuf//:protoc_lib (host)
|   @com_google_protobuf//:protobuf (host)
|   @com_google_protobuf//:src/google/protobuf/unittest_proto3_arena.pb.h (host)
|   @com_google_protobuf//:cc_test_protos_genproto (host)
|   @com_google_protobuf//:cc_wkt_protos_genproto (host)
|   @com_google_protobuf//:wrappers_proto (host)
`-- @com_google_protobuf//:protoc (host)
This cycle occurred because of a configuration option
ERROR: Analysis of target '//main:t1.out' failed; build aborted

**Comment by storypku** [comment]
> I download the Protobuf repo to my local computer,
> and in the workspace how do I configure it to compile with Bazel.
> Workspace has the following contents
> local_repository(
> name = "com_google_protobuf",
> path = "/home/ws/protobuf-3.12.3/",
> )
> What else do I need to configure.Thanks

This issue is about `Protobuf` and `Bazel`. Maybe you should take a look at https://github.com/bazelbuild/rules_proto for how to compile proto targets using Bazel. 

If you want to understand how Apollo use Bazel for building proto targets, see: [WORKSPACE:L18](https://github.com/ApolloAuto/apollo/blob/master/WORKSPACE#L18) , [third_party/protobuf/workspace.bzl] (https://github.com/ApolloAuto/apollo/blob/master/third_party/protobuf/workspace.bzl) and [scripts/proto_build_generator.sh](https://github.com/ApolloAuto/apollo/blob/master/scripts/proto_build_generator.py).

This issue should be closed now as it has little to do with Apollo. If you has other questions, please feel free to create another issue.
