### ISSUE TITLE
Several questions about how to set Control module parameters

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#12124]
When I try to tuning Control module, there are several parameters that i can't understand well.
1.“enable_steer_mrac_control”:In which situation that we need to use mrac controller?
2.“max_abs_speed_when_stopped”in vehicle_param.txt file represent what? In other words,what's the meaning of this flag? And "standstill_acceleration", "brake_minimum_action" in control_conf.pb.txt。 What's the difference between them?

Thank you for reading my questions carefully.

**Comment by kevin-y-wang** [comment]
Thanks for the questions for the Apollo Control module!

The answers to your questions:

(1) enable_steer_mrac_control can be enabled if there is non-neglected dynamics and time-latency in the by-wire steering mechanism in the autonomous vehicle (i.e., there are delay dynamics or time latency between the steering command and actual steering feedback from chassis). The MRAC control is used to offset the dynamic delay brought from the by-wire steering system. 

(2) max_abs_speed_when_stopped: because the speed measurement/estimation accuracy from the vehicle chassis or IMU is limited, there may be very small speed even if the vehicle is at or almost at the stop mode. This flag is used to judge if the vehicle can be treated as stopped (speed < max_abs_speed_when_stopped, then stopped).
standstill_acceleration: when the car parks at the parking gear, there must be some small braking command (i.e., the negative acceleration command) to hold the car at "standstill" status and avoid the car to slip forward. This parameter is used to define the  "anti-slipping" acceleration command at the parking mode. 
brake_minimum_action: used to define the minimum realizable brake action by by-wire mechanism. For most of vehicles it is set to 0 by default. 

Please let us know if you get any further questions. Thanks.
