### ISSUE TITLE
您的pointpillar代码有问题

### ISSUE THREAD

**Issue by liuchengs** [ApolloAuto/apollo#12312]
**Describe the bug**
连续跑同一帧点云，得到的结果不一样，而且越来越少。
麻烦看一下是不是哪个参数没有清。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeroldchen** [comment]
Hi @liuchengs , can you please post steps to reproduce the problem you met? I need more information to find out the cause.

**Comment by liuchengs** [comment]
dev_filtered_score_没有清，连续帧会丢物体，这个bug挺明显的。

**Comment by jeroldchen** [comment]
@liuchengs Thank you for your report! 
1. `dev_filtered_score_` is defined, allocated GPU memory and freed in point_pillars.cc. In postprocess_cuda.cu, this variable is used to save the output scores of anchors that are higher than a threshold. In the meantime, the number of these filtered anchors is recorded through a variable `dev_filter_count`. The original values in these positions are thus replaced. After that, only those filtered scores are used.
2. The problem you mentioned above that some obstacles cannot be detected sometimes is because of instability of the model. We are working on improving the stability of PointPillars model.

Hope you are satisfied with my answer. Thank you for your interest in Apollo.

**Comment by liuchengs** [comment]
I think you did not clear "dev_filtered_score", which would lead to object loss.
Please run same ply file for 10 times and check whether get the same result.

Best wishes

**Comment by jeroldchen** [comment]
[https://github.com/ApolloAuto/apollo/blob/4136473e57ed71a2acfaa77a20dbaca7ab67d3ad/modules/perception/lidar/lib/detection/lidar_point_pillars/postprocess_cuda.cu#L97](url)

>     filtered_score[counter] = top_score;

As shown by the above code, `filtered_score` is overrode every time detecting obstacles from a frame. Only anchors within `counter` can be processed in the next step, so as their scores which are saved in `dev_filtered_score`.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
