### ISSUE TITLE
Is there a way to split an opendrive file of a large map into multiple small opendrive files

### ISSUE THREAD

**Issue by XieJinLiang** [ApolloAuto/apollo#12359]
hello,
Is there a way to split an opendrive file of a large map into multiple small opendrive files?That is, split a large area map file into multiple small map files, all expressed in opendrive file format

**Comment by jinghaomiao** [comment]
@XieJinLiang we don't have the tool to split a map file into smaller ones because Apollo doesn't support hot swap of maps during execution times. We'll keep everyone posted if there's any change on that in the future. This issue is being closed. Please feel free to raise new issues if needed. Thanks for using Apollo.
