### ISSUE TITLE
Feature request: resume the partially downloaded files when restarting/rerunning docker/scripts/dev_start.sh.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12510]
Hi,

There are many and huge files will be retrieved by docker/scripts/dev_start.sh. But based on my observations, the partially downloaded files by this script will not be resumed when I  restart/rerun the script. So I think we should add the resume capability to this script for the partial downloaded files.

OTOH, I try to figure out the downloader used by this script but can't find any clue and I can't confirm whether it use the curl/wget as the backend. 

Any hints for this problem?

Regards,
HY

**Comment by storypku** [comment]
The  Docker volumes were downloaded and managed by `docker pull`. Docker has its own way to determine whether the specified volume was up-to-date.

If you have trouble downloading those volume, maybe you should try  the `-l` option  when running `dev_start.sh`.

I personally don't think it's a good idea to handle what `docker` does, unless docker have the desired options already.

Thank you for supporting Apollo. This issue is going to close now. If you have other questions, please feel free to open another issue.
