### ISSUE TITLE
[planning] stopped on top of the crosswalk.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#12511]
Hi team,

I ran some testings with LGSVL and Apollo 5.0 stack. 
and came across this issue where Apollo stopped on top of the crosswalk. 

Here's runtime video
* [video_1](https://drive.google.com/file/d/18ZdBs4BuatHXUA8MORc2EY1Kmpud6yTw/view?usp=sharing) 
* [video_2](https://drive.google.com/file/d/18JY5G1hmuKLAxbZdJD4coElTjxllKVF8/view?usp=sharing)

Here's runtime [recording](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EShF6U4WCcJCv1sjkPyCxhEBtZKvoez4akhSgLM2F809gA?e=9GfXeW) with `cyber_recorder`

**Steps to Reproduce**
1. start Apollo 5.0 docker containers 
2. start `bootstrap.sh`
3. open browser, select vehicle `Lincoln2017MKZ` and map `Borregas Ave`
4. `cyber_recorder play -f xxx.rec.0000 -l` 

**Expected behavior**
When there is a pedestrian crossing, even though it's a green light, Apollo should stop early to give way, instead of braking late and eventually stopped on top of the crosswalk ...

**Desktop (please complete the following information):**
 - OS: Ubuntu 1804
 - Browser chrome

**Comment by jmtao** [comment]
@ntutangyun based on the position/heading/speed of the pedestrian, the predicted trajectory of this pedestrian (the yellow line) crosses ADC's trajectory until ADC gets too close.  If it doesn't cross ADC's trajectory within our planning time scope, planning thinks it would be safe to ignore it. That's why the STOP decision shows up pretty late. There's always improvements(on perception, prediction, and planning) on how we decide when we shall stop for pedestrian. We'll continue to explore it in future release.  BTW, I'm a big fan of JJ, your profile pic LOL.
