### ISSUE TITLE
Mapshow Tools Error 

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#12537]
**Describe the bug**
Unable to run mapshow tool

Traceback (most recent call last):
  File "modules/tools/mapshow/mapshow.py", line 23, in <module>
    from modules.tools.mapshow.libs.localization import Localization
  File "/apollo/modules/tools/mapshow/libs/localization.py", line 23, in <module>
    from modules.localization.proto.localization_pb2 import LocalizationEstimate
ModuleNotFoundError: No module named 'modules.localization.proto.localization_pb2'

**To Reproduce**
1. Build Apollo
2. source scripts/apollo_base.sh
3. python modules/tools/mapshow/mapshow.py -h

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by storypku** [comment]
> 3\. modules/tools/mapshow/mapshow

Since all Python files were managed by Bazel in master HEAD, `bazel-bin/modules/tools/mapshow/mapshow` should be used instead of the original python script.

And this is in uniform: when you try to run `path/to/python/script.py` in Apollo master, just run `bazel-bin/path/to/python/script`. If you found any python binary don't conform to this rule, welcome to open an issue.

**Comment by agarwalsid** [comment]
Thanks @storypku, will keep that in mind.

**Comment by storypku** [comment]
> Thanks @storypku, will keep that in mind.

FYI: I have a specific PR #12564 to have this documented.
