### ISSUE TITLE
Conti Radar driver question

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#12552]
Hi team!  
Can You answer me if it's not difficult?  
Can I use [this](https://www.peak-system.com/PCAN-USB-Pro-FD.366.0.html?&L=1) device for launch a [radar driver](https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/radar/conti_radar/launch/conti_radar.launch)?  

I changed this [file](https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/radar/conti_radar/conf/conti_radar_conf.pb.txt)  

```
can_conf {

  can_card_parameter {
    brand:SOCKET_CAN_RAW
    type: USB_CARD
    channel_id: CHANNEL_ID_ZERO
  }

  enable_debug_mode: false
  enable_receiver_log: false
}
```
But, when I run the driver, I cannot get data from the radar

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: **Linux Ubuntu 18.04**
- **Apollo installed from (source or binary)**: **source**
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: **master**

**Comment by jinghaomiao** [comment]
The driver is only tested to work for Conti radar with CAN interface. If you have radars from other manufacturers or with different interfaces, you have to make sure that CAN messages are correctly parsed with the given driver (mostly likely not and you need to implement your own driver).

This issue is being closed. Should you have other issues, please feel to raise new ones. Tnanks for using Apollo.
