### ISSUE TITLE
[planning] Apollo stops for pedestrian behind. 

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#12556]
Hi team,

I ran some testings with LGSVL and Apollo 5.0 stack.
and came across this issue where Apollo stopped for a pedestrian it already passed. 

Here's [video](https://drive.google.com/file/d/19aToqtR1Ku9Gm4TR8HLvWUSJcKEAlWIz/view?usp=sharing)
Here's runtime [recording](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EZ2Nkd13wHhCj_Ow-4bkcO8BSdum8IX46GJpt0RLn6YLqg?e=xrytM0) with cyber_recorder

**Steps to Reproduce**

start Apollo 5.0 docker containers
start bootstrap.sh
open browser, select vehicle Lincoln2017MKZ, and map Borregas Ave
cyber_recorder play -f xxx.rec.0000 -l

**Expected behavior**
Since Apollo has already passed the pedestrian, I'm not sure why it still chose to brake for the pedestrian crossing behind. 

**Desktop**

OS: Ubuntu 1804
Browser chrome

**Comment by jmtao** [comment]
@ntutangyun this is as expected. based on the position/heading/speed of the pedestrian, planning makes the decision to stop for the pedestrian. When the stop wall shows up, the pedestrian is still ahead of ADC longitudinally.  But because of the safety longitudinal distance between ADC and the pedestrian, the stop wall falls on the ADC body and would cause hard brake.  We can improve this in future release (probably by ignoring this pedestrian in this case, not sure still need to investigate further to see how safe it is). For now, safety is our #1 consideration. You should stop when you should.
