### ISSUE TITLE
Communication between components in different nodes

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#12704]
Hi, 
I trying to understand how works the communication between components in different nodes. I know that they communicate through shared memory and, in particular, the writer has a transmitter and the reader has a receiver. The reader reads the message from the message queue in the [blocker](https://github.com/ApolloAuto/apollo/blob/master/cyber/blocker/blocker.h). But how the messages is written in this queue. Which class takes the message written by the writer/transmitter and put it in the blocker queue?

**Comment by daohu527** [comment]
## Process
Generally speaking, the approximate process is like this
```
node -> writer -> transmitter -> notifier  <-> receiver
```
When node starts need create `writer`, and then send msg through writer by `transmitter`. Transmitter then notification reader to read the message.  

You should learn more about concepts of the publish-subscribe model so that you can understand it better. Like
* **Node** - node contains readers and writers
* **Channel** - define by topic, represents a publish-subscribe relationship
* **Publish&Subscribe** - will join the corresponding topology
* **Observer pattern** - Observers will observe changes and notify subscribers

## Notes
By default, we use `HybridTransmitter`, and there are three transmitter distinguished by the following function

https://github.com/ApolloAuto/apollo/blob/51651b9105e55c14e65cc2bd349b479e55fffa36/cyber/transport/transmitter/hybrid_transmitter.h#L298-L310

* **DIFF_HOST** - across physical machines, transmission over the network through `fastrtps`
* **DIFF_PROC** - same physical machines, through shared memory
* **SAME_PROC** - same thread, through memory and no need to serialize and deserialize

**Comment by Turi30** [comment]
Which of those components is a task or a thread timer-based or event-based?

> ## Process
> Generally speaking, the approximate process is like this
> 
> ```
> node -> writer -> transmitter -> notifier  <-> receiver
> ```
> 
> When node starts need create `writer`, and then send msg through writer by `transmitter`. Transmitter then notification reader to read the message.

**Comment by daohu527** [comment]
`writer` is called by the module. Whether it is a thread or a coroutine depends on the module. 

1. If it's a `TimerComponent` then write in a period.  
2. If it's a `cyber::Component<>` then drive by messages.  

and all modules are **coroutines**.

**Comment by oska874** [comment]
Communication is  base on fast-rtps.

**Comment by Turi30** [comment]
Notifier is created by the reader or the writer? And how the notifier knows that there is a new message? Who schedules the notifier coroutines?

**Comment by daohu527** [comment]
Notifier is called by the writers.  Writers send the msg to dispather and then notifier readers. the whole process is schedules by cyber.
