### ISSUE TITLE
About the MSF in apollo.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12729]
Hi,

I've learned [this paper](https://arxiv.org/abs/1711.05805) relevant to the MSF implemented in Apollo. MSF is a localization scheme that contains many components and possible combinations, why this paper only select these specific methods for its implementation in Apollo?

Regards,
HY

**Comment by renlancai** [comment]
@hongyi-zhao , Thanks for your question. As you said, more sensors integrated into MSF could improve the reliability and availability for the whole solution, and we do now (2020) employ more sensors like cameras to the list. But dated back to 2018,  due to the limited computing resource and available sensor suit, we only chose the RTK/LiDAR/IMU combinations. You can follow our latest progress on vision in paper(DA4AD: End-to-end Deep Attention Aware Features Aided Visual Localization for Autonomous Driving) for more details. Thanks again.

**Comment by hongyi-zhao** [comment]
@renlancai I find this paper [here](https://arxiv.org/abs/2003.03026) according to your guidance. But it seems that you are not in the list of authors. Are you a member of the research group which published this paper?

**Comment by zhouyao4321** [comment]
@hongyi-zhao The [paper](https://arxiv.org/abs/2003.03026) @renlancai mentioned proposed a camera based localization module which can add to MSF. This camera based localization module has the same input/output as the LiDAR localization module, so it's easy to be integrated into MSF. Back to your original question, in 2018, due to the limited computing resource and available sensor suit, we only chose the RTK/LiDAR/IMU combinations to build the MSF scheme.
