### ISSUE TITLE
Problems with navigation mode in launch example

### ISSUE THREAD

**Issue by liversonp** [ApolloAuto/apollo#12739]
**Describe the bug**
When I tried to launch the demo_3.5.record using navigation mode in Apollo 6.0, my car didn't move

**To Reproduce**
1. Follow Apollo's install guide
2. Do How to Run and Start Apollo steps
3. Open http://localhost:8888/
4. Change the setup mode to navigation
5. Do replay demo record commands

**Expected behavior**
See apollo running the record with navigation mode normally like any other mode

**Screenshots**
![Captura de tela de 2020-10-08 17-20-54](https://user-images.githubusercontent.com/45077010/95509342-bdd63100-098a-11eb-845e-d866793b7616.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Browser: Google Chrome and Mozilla Firefox

**Comment by ds-ssj** [comment]
I encounter the same problem, even there are no traffic lights in the scenery.

**Comment by duongnxptit** [comment]
I am encountering the same problem now. Have someone has solution for it?

**Comment by storypku** [comment]
Dear all, sorry for the confusion this issue caused you.
I have asked other team members and updated the document in PR #12862 .

The original doc seems to be for Apollo 2.5, and haven't been updated ever since. Now that `demo_3.5.record` is used, the corresponding Drive Mode and Map should be updated accordingly.
