### ISSUE TITLE
Is there any way to see some terminal output while running?

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#12794]
I want to print on terminal some information during the execution. Is there any way?

**Comment by daohu527** [comment]
If you only need to debug, the easiest way is use `AERROR` instead of `AINFO`

**Comment by Turi30** [comment]
Using `AERROR` where I can see the information?

**Comment by daohu527** [comment]
How did you start the module? 
1. If you use dreamview, there is no output to console. Because it call `std::system`
https://github.com/ApolloAuto/apollo/blob/10bac81cc272dfa2bec13875bb0342848bd933d0/modules/dreamview/backend/hmi/hmi_worker.cc#L126-L134

2. If you use ` cyber_launch start modules/routing/launch/routing.launch
`, logs greater than the info level will be output to the console. You can also output the info log level to console use `GLOG_alsologtostderr=1`, but there will be a lot of logs, I think you may not need most of them. So ues the `AERROR` will be better for debug.
https://github.com/ApolloAuto/apollo/blob/eb2761c0fb1100d1a4a457520e7685fcadc85788/cyber/setup.bash#L37-L40

**Comment by Turi30** [comment]
> 2. If you use `cyber_launch start modules/routing/launch/routing.launch`, logs greater than the info level will be output to the console. You can also output the info log level to console use `GLOG_alsologtostderr=1`, but there will be a lot of logs, I think you may not need most of them. So uses the `AERROR` will be better for debug.
>    https://github.com/ApolloAuto/apollo/blob/eb2761c0fb1100d1a4a457520e7685fcadc85788/cyber/setup.bash#L37-L40
To use this method, how should I compile apollo? 
I give these commands:
1. `./docker/scripts/dev_start.sh`
2. `./docker/scripts/dev_into.sh`

3. `./apollo.sh build` or should I put build_dbg option? 
4. At the end `./scripts/cyber_launch.sh start`?

**Comment by daohu527** [comment]
You can refer to the official documentation to start apollo. [doc](https://github.com/ApolloAuto/apollo/blob/r5.5.0/docs/howto/how_to_build_and_release.md#build-apollo) 
Then use cmd like below
```
cyber_launch start modules/routing/launch/routing.launch
```
