### ISSUE TITLE
canbus_teleop.sh can not control the car

### ISSUE THREAD

**Issue by Amazingmum** [ApolloAuto/apollo#12801]
### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (5.5,)**
你好我用canbus_teleop.sh 测试小车的底盘和apollo系统是否配置好。apollo系统是可以读取小车的底盘信号。在测试时，用kvazer工具一端连接工控机一端连接kvazer的客服端查看信号来测试工控机是否下发了指令。这样怎么让系统进入自动驾驶模式？用teleop键盘控制时，没有发现工控机下发了指令呢。

**Comment by Shen-Kirren** [comment]
@liukr001 请问你这个问题现在解决了吗？我也是发现控制指令一直是0无法改变

**Comment by liukr001** [comment]
解决了。是我的底盘代码的逻辑没设置好。可以用来测试

**Comment by Shen-Kirren** [comment]
@liukr001 方便说一下是哪部分的逻辑吗

**Comment by liukr001** [comment]
底盘错误逻辑，进入自动驾驶模式
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shen qi ***@***.***&gt;; 
发送时间: 2021年3月16日(星期二) 晚上9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ApolloAuto/apollo] canbus_teleop.sh can not control the car (#12801)





 
@liukr001 方便说一下是哪部分的逻辑吗

**Comment by liukr001** [comment]
不客气。加个微信多多交流吧
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shen qi ***@***.***&gt;; 
发送时间: 2021年3月30日(星期二) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ApolloAuto/apollo] canbus_teleop.sh can not control the car (#12801)





  
底盘错误逻辑，进入自动驾驶模式
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "shen qi @.&gt;; 发送时间: 2021年3月16日(星期二) 晚上9:19 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [ApolloAuto/apollo] canbus_teleop.sh can not control the car (#12801) @liukr001 方便说一下是哪部分的逻辑吗 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
多谢，我也是类似的问题，已解决
