### ISSUE TITLE
Automatically Enabling Sim Control

### ISSUE THREAD

**Issue by EricWu416** [ApolloAuto/apollo#12819]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5

Is there a way to enable sim control without manually turning it on manually on a browser? I tried modifying the `modules/dreamview/conf/dreamview.conf` file by appending `--enable_sim_control=true` but it does not work in my case. The sim control remains off after restarting Apollo. Thanks!

**Comment by daohu527** [comment]
You can try 
https://github.com/ApolloAuto/apollo/blob/4e0326d19571d6c5e363854ef93da275384bb6cc/modules/dreamview/frontend/src/store/config/parameters.yml#L106-L107

**Comment by EricWu416** [comment]
@daohu527 Thanks for the quick response! I modified it to true, restarted the container, and build apollo again, but sim control still defaults to disabled when I opened up Dreamview. I have to manually toggle sim control to enable it on the browser. Is it possible that additional steps are required?

**Comment by daohu527** [comment]
Pls search the `enableSimControl` in dreamview module, and find the value, there are multi places and the quick way is to find if the all value is true.

**Comment by EricWu416** [comment]
@daohu527 I found two occurrences of `enableSimControl` where I can set values: `modules/dreamview/frontend/src/store/config/parameters.yml` and 'modules/dreamview/frontend/dist/parameters.json'. I made sure they are both set to true, pulled the containers again, and rebuild apollo. SimControl was still off when I opened Dreamview on my browser.

**Comment by daohu527** [comment]
## why config not work?
The dreamview is composed of backend and frontend, the frontend is truely work as you see **the toggle is enabled then soon disabled** because the backend sync the status to frontend. below is the code.

https://github.com/ApolloAuto/apollo/blob/0e6c0c7f8b0e0e4e801332a30a01975030bfda3e/modules/dreamview/backend/simulation_world/simulation_world_updater.cc#L60-L66

## how to enable?
So if the backend will sync the status, and the frontend just a status display. So the really sim_control is behind in the backend, and if you set the toggle in the frontend, will send a websocket cmd to backend, which will start sim_control. Then the focus is how to enable sim_control in the backend.

You can modify the sim_control code to enable the sim_control by default. but I don't think this is really you need.

## what you really need?
I I have implemented similar functions, automated test modules such as planning modules. But you need to play bag and open sim_control synchronously. If you don't then this is meaningless, Because the sim_control will be initialized at the beginning, and if it starts early before playing the bag, there is no message for sim_control to initialize localization.

https://github.com/ApolloAuto/apollo/blob/10bac81cc272dfa2bec13875bb0342848bd933d0/modules/dreamview/backend/sim_control/sim_control.cc#L246-L257

## how to implement?
You can write a new module we say "sim_play", then Integrated play bag module and sim_control module. You can then control to first play bag and then find the localization and car status to init sim_control, and then start it.

Hope to help you!

**Comment by EricWu416** [comment]
@daohu527 Thanks for the detailed explanation! It is really helpful and informative. I modified the code as you suggested, and now SimControl is enabled by default. I am writing a script that automates stuff for my research group, so I wish that it is able to run SimControl without us enabling it manually.

**Comment by MaisJamal** [comment]
In the same context, while writing a script to automate experiments with simcontrol, I need to choose one vehicle to be always chosen by default. 
I lack experience in backend applications, so can you please guide me on how/where to choose a default vehicle in the code ?

**Comment by daohu527** [comment]
what do you mean about "I need to choose one vehicle to be always chosen by default."? I don't understand the function you are talking about

**Comment by MaisJamal** [comment]
I need vehicle Lincoln and some mode to be by default in dreamview. rather than choosing it manually every time and then turn simcontrol on

**Comment by daohu527** [comment]
## method
There are two methods, but I recommend the latter

1. You can add below code to set default vehicle in `HMIWorker::InitStatus()`
```
ChangeVehicle("vehicle name")
```
2. You can just modify the default config in `vehicle_param.pb.txt`
```
DEFINE_string(vehicle_config_path,
              "/apollo/modules/common/data/vehicle_param.pb.txt",
              "the file path of vehicle config file");
```

**Comment by MaisJamal** [comment]
Thanks a lot. This was so helpful.

**Comment by icolwell-as** [comment]
Another question on the same subject. Why is there duplication between the following files:
`apollo/modules/calibration/data/mkz_example/vehicle_param.pb.txt`
`apollo/modules/common/data/vehicle_param.pb.txt`

They both seem to contain similar information.

**Comment by daohu527** [comment]
## reason
You know that there are multiple configs in "modules\calibration\data", which means you can use differenct configurations for different cars. 

When you choose a car in dreamview then it will automally modify the configuration in the corresponding file to adapt to different models of cars.

**Comment by icolwell-as** [comment]
Thanks for the response @daohu527! Wouldn't it be best for `apollo/modules/common/data/vehicle_param.pb.txt` to be gitignored since it may change based on vehicle in use? or is it simply left in the repo as a sort of default placeholder?

**Comment by daohu527** [comment]
There is indeed a problem with git because it changes files. I haven't thought of a good way yet

**Comment by shandaolu** [comment]
> ## why config not work?
> The dreamview is composed of backend and frontend, the frontend is truely work as you see **the toggle is enabled then soon disabled** because the backend sync the status to frontend. below is the code.
> 
> https://github.com/ApolloAuto/apollo/blob/0e6c0c7f8b0e0e4e801332a30a01975030bfda3e/modules/dreamview/backend/simulation_world/simulation_world_updater.cc#L60-L66
> 
> ## how to enable?
> If the backend will sync the status, and the frontend just a status display. So the really sim_control is behind in the backend, and if you set the toggle in the frontend, it will send a websocket cmd to backend, which will start sim_control. Then the focus is how to enable sim_control in the backend.
> 
> You can modify the sim_control code to enable the sim_control by default. Like
> 
> ```
> SimControl::SimControl(const MapService* map_service)
>     : map_service_(map_service),
>       node_(cyber::CreateNode("sim_control")),
>       current_trajectory_(std::make_shared<ADCTrajectory>()) {
>   InitTimerAndIO();
>   Start();      // start by default
> }
> ```
> 
> But I wonder what is your purpose for doing this
> 
> Hope to help you!

我是否可以向后端写入数据自动化启动dreamview。我目前通过websocket与ws://localhost:8888/websocket 建立了联系，但是我发送如下数据是{"type": "ToggleSimControl", "enable": "true"}，显示器并没有触发sim control. 想请教一下如何解决？
