### ISSUE TITLE
Functions of Path_decider and Speed_decider in the Planning module

### ISSUE THREAD

**Issue by xiaozhe90** [ApolloAuto/apollo#12907]
Hi team,

I cannot really understand the functions of the tasks Path_decider and Speed_decider. They are both adding "decisions" like "ignore", "stop", "follow", "yield", "overtake", "nudge" to obstacles which is a menber of path_decions under reference_line_info. But do these "decisions" really have functions in the planning process except the "ignore" decision?  Futher more, since both these tasks were executed at the very last stage of the path and speed decision make stages; does this mean even the "ignore" decisions they made are not functional? So are these two tasks just for debug information generation? Am I wrong?

Many thanks

**Comment by jmtao** [comment]
@xiaozhe90 (1) we consolidate all the decisions for individual obstacle/object to a main decision. （2）we condolidate multi decisions on the same obstacle/object (3) the decisions on obstacles/objects are also for visualization purpose, so that we know the intention of the planning module.  the path data(trajectory points with position, speed and etc) behind these decisions are the actual data to be used and consumed by later planning steps. e.g. for a STOP decision, the path is planned to end before the stop position; for YIELD decision, the speed is planned to yield to the corresponding moving obstacle...
