### ISSUE TITLE
why APOLLO still using osqp 0.5.0？

### ISSUE THREAD

**Issue by Tinnk** [ApolloAuto/apollo#13030]
![image](https://user-images.githubusercontent.com/25147500/99494242-a340a000-29ab-11eb-8bf6-f4de126a5465.png)
The latest version of osqp is 0.6.0, but we are still using 0.5.0. Is there any bug within the new version? In the code, 0.6.0 has been commented out. Thanks! :)

**Comment by storypku** [comment]
> ![image](https://user-images.githubusercontent.com/25147500/99494242-a340a000-29ab-11eb-8bf6-f4de126a5465.png)
> The latest version of osqp is 0.6.0, but we are still using 0.5.0. Is there any bug within the new version? In the code, 0.6.0 has been commented out. Thanks! :)

Hi @Tinnk , this is because osqp 0.6.0 comes with breaking changes from 0.5.0. Its [release notes](https://github.com/oxfordcontrol/osqp/releases/tag/v0.6.0) says:

```
1) Changed syntax of osqp_setup function.
2) osqp_setup function requires P to be upper triangular. 
```

So we had to use 0.5.0 when Apollo 6.0 releases.

Wait for comments from other team members.
@yifeijiang @jmtao @JasonZhou404 @Capri2014 @HongyiSun

**Comment by Capri2014** [comment]
yes, that's right .
