### ISSUE TITLE
In the navigation mode, open the "Planning" module and other related modules, and click "Start Auto", and the vehicle will not be controlled

### ISSUE THREAD

**Issue by yufeilongyuan** [ApolloAuto/apollo#13148]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
Problem description：
1.We are manually recorded reference line, and then through the modified navigator.py script sent.We use version 5.5, Ubuntu 16.04.
2.When automatic driving is turned on, the vehicle is always uncontrolled and moves to the right.However, we have no problem in RTK tracing test.
3.I found some strange phenomena. I showed them with pictures.
4.It should be noted that some modules are opened through the terminal.

![b049cd0437c1dbf032c282e888fc276](https://user-images.githubusercontent.com/23471410/101457623-ba522c80-3970-11eb-8d21-3f8eeda41e11.jpg)
First of all, there is an extra green line on the map in the upper left corner, This extra green line is always flashing, not always appearing.which does not match the reference line. And the actual test found that the vehicle seems to be looking for this line, not the reference line we want. Secondly, in dreamview, there is an extra group of line segments, which are both white and yellow.

![c391345b6807e838979a83383d887e3](https://user-images.githubusercontent.com/23471410/101458136-73b10200-3971-11eb-8f0d-2e596ee26560.jpg)
This is our channel information. I don't know if some information is missing.

![1607415955(1)](https://user-images.githubusercontent.com/23471410/101458712-300ac800-3972-11eb-99e8-dfc26175726a.jpg)
This is our profile

![15af9cc44a13bbd57f99075098eb3d8](https://user-images.githubusercontent.com/23471410/101460277-5a5d8500-3974-11eb-9b27-b742f52ea787.jpg)
![a008483daf15283a9c0586ece116f22](https://user-images.githubusercontent.com/23471410/101460292-5fbacf80-3974-11eb-8532-0085f63234fc.jpg)
There are always more things we don't need.

Now, I really need the official help. Thank you. Expect a reply

**Comment by jiayisong** [comment]
Is it a bug in apollo's code？

**Comment by VictXue** [comment]
We have a similar problem. Have you solved it?

**Comment by yfl1991** [comment]
Hello, brother. Sympathize with you, I also encountered the same problem, can not solve, give up. I thought only I could meet, but you did. Hope you can solve it. Don't forget to inform me. Thank you

**Comment by yufeilongyuan** [comment]
> Is it a bug in apollo's code？

I don't know, but I'm in trouble.

**Comment by yufeilongyuan** [comment]
> We have a similar problem. Have you solved it?

NO, and I'm in trouble.

**Comment by yufeilongyuan** [comment]
> Hello, brother. Sympathize with you, I also encountered the same problem, can not solve, give up. I thought only I could meet, but you did. Hope you can solve it. Don't forget to inform me. Thank you

It's luck, man.

**Comment by github-luffy** [comment]
We have encountered a similar problem, have you solved it

**Comment by yufeilongyuan** [comment]
> We have encountered a similar problem, have you solved it



> We have encountered a similar problem, have you solved it

NO, and I'm in trouble.

**Comment by yufeilongyuan** [comment]
**Supplementary note:** after verification, the extra green straight line finally points to the point with zero longitude and latitude.

**Comment by storypku** [comment]
@liouyx @guoweiwan @JasonZhou404 Would you please help with this issue?  It seems that several developers encounter this problem.

**Comment by yufeilongyuan** [comment]
The problem has been solved, thank you.

**Comment by jp12AI** [comment]
@yufeilongyuan It seems that you have had success running navigation_mode on a newer version of apollo (5.5). I am having issues sending navigation line data to dreamview. I collect the bag/record file by enabling these modules: relative map, localization, and record and I replay it and the map seems to move along with the speed but the car doesn't move in the replay. Then when I send the navigation line bag I get the error pictured below. I use this command: bash scripts/navigator.sh data/bag/(file). Am I doing everything correctly? Enabling the right modules to collect the bag? I followed the 2.5 tutorial and it is not useful for the newer versions. The smoother tools don't work because they rely on rosbag. How are you doing this process? Collecting and successfully sending the navigation line? What commands and modules need to be enabled? Any help/input on how you do this would be greatly appreciated as I have been stuck on this issue for a long time. I am using LGSVL simlator and version 5.0. 
![Screenshot from 2021-09-05 14-04-56](https://user-images.githubusercontent.com/58639429/132141716-25ff53b3-c62e-44f8-b0cd-25ae9832fef6.png)
This is the error received when trying to send line data. The replay works fine (it seems) Thank you again
