### ISSUE TITLE
How to generate a release package

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#13394]
A software package include all the "conf,dag ,launch, data file, bin,lib and the scripts". but not the whole docker image.
So I can bring apollo system up  in a whole new docker image.

In the latest master branch, the apollo.sh provide a release option. But it only contain limited  files.
What the purpose of this fuction? How to use it correctly to satisfy my request?

**Comment by storypku** [comment]
As Apollo depends heavily on other system-provided/installed-from-source packages,  no standalone "binary package" of Apollo will be provided as opposite to most other packages.

The `apollo.sh release` command aims to generate binary distribution for Apollo. You can think it as bazel's way of `make install`.  However, the current `apollo.sh release` implementation is still in its early stage, a lot of work need to be done to make it usable with Apollo Runtime Docker container (so that uses didn't need to compile the whole project before he/she can run commands/binaries).

**Comment by sinopec** [comment]
> As Apollo depends heavily on other system-provided/installed-from-source packages, no standalone "binary package" of Apollo will be provided as opposite to most other packages.
> 
> The `apollo.sh release` command aims to generate binary distribution for Apollo. You can think it as bazel's way of `make install`. However, the current `apollo.sh release` implementation is still in its early stage, a lot of work need to be done to make it usable with Apollo Runtime Docker container (so that uses didn't need to compile the whole project before he/she can run commands/binaries).

Thanks for reply .
This "apollo.sh release" function just seems to be my requirements, Hope it to be ready  soon.

**Comment by storypku** [comment]
Hi @sinopec , I am going to close this issue now. Once release build becomes ready, we should get everyone noticed.
If you have other questions, please feel free to open another issue.
Thanks for using Apollo.
