### ISSUE TITLE
How to use mock_routing_request.py in Apollo 5.0 (LGSVL)? Any other solution to force AD vehicle to change lanes?

### ISSUE THREAD

**Issue by Alejandro-A-R** [ApolloAuto/apollo#13592]
### System information

- OS Platform and Distribution: Linux Ubuntu 20.04
- Apollo version: 5.0 (LGSVL fork)

### Steps to reproduce the issue:
- I am pretending to use the mock_routing_request.py script in order to send routing requests to the Autonomous Driving (AD) vehicle, so that it changes lanes (by sending an end waypoint located on the left or right lane) depending on the situation (i.e. if there is an NPC which has to overtake the AD vehicle and the AD vehicle is on the left lane). This strategy will only be feasible if it is possible to run the mock_routing_request.py script from one of the scripts that are attached either to the AD vehicle (VehicleController.cs) or the NPC vehicles (NPCLaneFollowController.cs). Note that, in my particular case, I would need just two different routing requests in terms of the final waypoint: one located on the left lane and other on the right lane, since the AD vehicle will be circulating by the same road, which is composed by two lanes. As far as I have understood, the start waypoints can be fixed, as long as they are located behing the AD vehicle, but correct me if I am wrong and it is necessary to set them as the current location of the AD vehicle.
- So, my questions regarding this matter are the following:
    - How is mock_routing_request.py properly used? This includes from where and with which command should it be run, so that 
    it successfully sends the routing request and whether or not the start waypoint can remain the same as long as it is located 
    behind the AD vehicle. I have not found this information properly explained in the related issues.
    - Is it possible to run mock_routing_request.py from a .cs script from the LGSVL simulator? In case it is possible, how should it 
    be done?
    - In case it is not possible to run mock_routing_request.py from the .cs scripts from LGSVL, is there any other strategy that 
    forces the AD vehicle to change lanes and that can be called from one of the .cs scripts from LGSVL?

**Comment by daohu527** [comment]
As far as I know, why don't you use lgsvl scripts to control the simulator, so that you can control the simulator and also access and control apollo. In fact, I highly recommend using scripts to control, which usually called a "scene runner".

**Comment by Alejandro-A-R** [comment]
Ok, then my question is, how can I send apollo a command so that it changes lanes (directly by ordering apollo to change lanes or by sending a routing request whose end point is located in the lane I want the apollo vehicle to change) using the LGSVL scripts?

Thank you in advance

**Comment by daohu527** [comment]
## solution
Actually, I repeat my thoughts to see if it can meet the requirements.
1. I think you should confirm the trajectory of your car in advance, this can be achieved through routing
2. Then add the trajectory of the obstacle, the trajectory of the obstacle is related to your test item
3. Changing the trajectory of the vehicle in real time is **determined by an algorithm, not by human control**. In fact, because the planning module changes the trajectory in real time according to the situation, it is difficult for you to control it. So it’s much easier to control obstacles to verify some scenarios

## send command
1. Because LGSVL's terminal is originally connected through a socket, you can run it on any machine
2. The easiest way is to run "mock_routing_request.py" in apollo docker, then run lgsvl scripts
3. Secondly, you can use the socket method like lgsvl to send routing commands to apollo through the websocket interface in dreamview

Hope this helps you!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
