### ISSUE TITLE
试配一辆新车

### ISSUE THREAD

**Issue by hxj0316** [ApolloAuto/apollo#13680]
Ubuntu 18.04    Apollo5.5
在按照https://github.com/ApolloAuto/apollo/blob/master/docs/technical_tutorial/apollo_vehicle_adaption_tutorial_cn.md所给出的详细文档进行试配一辆新车的过程中，我们写好了相应的DBC文件，但是，在借助Apollo自带的DBC转化工具gen.py进行DBC文件转换成canbus模板代码，执行代码cd modules/tools/gen_vehicle_protocol和python gen.py ge3_conf.ymal，结果出现如图所示的错误，麻烦问一下大家是什么原因呢？如何才能解决？谢谢~
![2021-04-10 21-50-59 的屏幕截图](https://user-images.githubusercontent.com/66103957/114289202-8a46a180-9aa8-11eb-8eac-a153542f52b1.png)

**Comment by daohu527** [comment]
## reason
There may be some special characters in the file, so when you yse shlex there's a fail. you can ref to [link](https://stackoverflow.com/questions/57483794/python-shlex-no-closing-quotations-error-how-to-deal-with)  

## fixed
Because I don’t know which line it is, I suggest you print out the content of this line before confirming the problem, you can add debug code in "modules/tools/gen_vehicle_protocol/extract_dbc_meta.py"
```python
        for line in fp:
            print line    # which will print the line failed 
            items = shlex.split(line)
```

**Comment by hxj0316** [comment]
那请问上面在gen.py里面的那两个问题又是什么情况呢？

**Comment by daohu527** [comment]
It's the same error, it's the error stack!!!

**Comment by hxj0316** [comment]
但是奇怪的是我在更换dbc文件以后就可以生成相应的控制逻辑和反馈逻辑，并且也没有报告上面的错误。

**Comment by daohu527** [comment]
It looks like a problem with the dbc file, you can find out which line of the dbc file is the problem by printing the above
