### ISSUE TITLE
Arm Aarch64 jetson support

### ISSUE THREAD

**Issue by yufeilongyuan** [ApolloAuto/apollo#13690]
Hi team：
             When can I compile the arm version of Apollo? Aarch64 or NVIDIA Jetson. thank you.
             Or do you have a time plan, about when to support these.

**Comment by storypku** [comment]
Hi @yufeilongyuan, thanks for your interest in Apollo on ARM64 platforms. 

Apollo on ARM64 was still a work-in-progress as of today, since there are still some  issues to fix to get it compiled. Even if compilation problems were all resolved,  making Apollo running on ARM64 boards still needs more work to do.
