### ISSUE TITLE
Apollo version R1.0.0 在vps上编译失败  

### ISSUE THREAD

**Issue by tianrking** [ApolloAuto/apollo#13705]
Ubuntu 20.04
Apollo version R1.0.0
ram 512m
1 cpu
build过程失败 提示删除 log后重新编译  再次编译则会出现死机
请问 1.是否是服务器性能不足导致 
2.Apollo系统配置最低要求是怎样呢
3.可否部署在云端服务器上以便于远程协同调试

**Comment by storypku** [comment]
Hi @tianrking, 

1) It seems from your description that the issue was caused by insufficient memory.

2) For Apollo 6.0+ and master, the recommended system configuration was: 

```
A machine with a 8-core processor and 16GB memory minimum
NVIDIA Turing GPU is strongly recommended
```
NVIDIA Ampere GPU was only supported in Apollo master.

3) Would you please specify your idea of cloud deployment of Apollo in a more detailed way?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
