### ISSUE TITLE
What is the lidar type fusion method CCRFSequenceTypeFusion?

### ISSUE THREAD

**Issue by Sam163** [ApolloAuto/apollo#13726]
Hi, Apollo team!
I am interested in learning data fusion techniques. Are there any articles or mathematical justification of method CCRFSequenceTypeFusion? I'm confused too (#13585) how to compose [CNNSegmentation and Confidence matrices](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/lidar/models/fused_classifier/classifiers.property) and [Transition matrix](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/lidar/models/fused_classifier/transition.property). And does CCRFSequenceTypeFusion really work correctly?

As I correctly understood, the method CCRFOneShotTypeFusion is needed to merge probabilities if the object was recognized by several neural networks. For these purposes, there are matrices DecisionForestClassifier and CNNSegmentation.
[At this point in the code](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/lidar/lib/classifier/fused_classifier/ccrf_type_fusion.cc#L115) you check whether the object is recognized by one method or not. But for the lidar component, you only use CNNSegmentation, and raw probabilities vector is always 1. What is the meaning of such a complex CCRFOneShotTypeFusion?

If your method really knows how to fuse data from different raw probabilities sets, it is great. But there are still questions about how to solve the problem with the "confidence" parameter of ''apollo::perception::base::Object". It is always the same for all raw probabilities.  You can verify that in [this code line](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/lidar/lib/classifier/fused_classifier/ccrf_type_fusion.cc#L110). Accordingly the question arises what is the mathematical meaning of the "Confidence smooth matrix"?
So the raw probabilites vector is always 1 and the confidence matrix is questionable. Wouldn't it be the same if you just get raw probability maximum instead of CCRFOneShotTypeFusion?

**Comment by jeroldchen** [comment]
Hi @Sam163 , thank you for your question. Really a good finding. Indeed the raw probability of object is always set to 1, which is somehow unreasonable. To make full use of CCRFOneShotTypeFusion, raw probabilities need to be saved for every category, and that is available because the CNNSegmentation model does output these probabilities.

For CCRFSequenceTypeFusion, we only use CNNSegmentation model to detect objects, so matrix of DecisionForestClassifier is not useful anymore.

Thank you again for pointing out these problems. We will update the related codes to make improvements on Lidar tracking module.
