### ISSUE TITLE
velodyne compensator error

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#13769]
env : ubuntu 18.04, apollo v5.5

I want to run the velodyne compensator. However, the following error occurs.
Transmit the /tf value to the channel through rtk localization.
I am currently unable to connect gps directly to velodyne.
So I am using "use_gps_time: false" in conf.
Please help me if there is a workaround. Thank you.

[gnss   ]  E0512 17:21:28.114421 15032 compensator.cc:34] [velodyne]Can not find transform. 1620841495541983000 frame_id:velodyne128 Error info: Lookup would require extrapolation into the future.  Requested time 1620841495541983000 but the latest data is at time 1620807688103493632, when looking up transform from frame [velodyne128] to frame [world]

**Comment by jeroldchen** [comment]
@phs4530 Seems that your GPS is not working normally. You can checkout the GPS status through `cyber_monitor`. Or you can use MSF localization instead of GPS by turning off the transform from NovAtel:
https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/drivers/gnss/conf/gnss_conf.pb.txt#L42-L46 .
Just set `enable: false` here.

**Comment by phs4530** [comment]
@jeroldchen 
Thanks for reply.
My GPS don't seem to have a problem...
I want to know why the time requested when converting coordinates is faster than the latest data received. 
Isn't the request for coordinate conversion after receiving the data?
Why is this happening?

I need a compensator lidar data to run the perception module.

**Comment by daohu527** [comment]
You also need to enable the tf module.
