### ISSUE TITLE
Perception module with HD map?

### ISSUE THREAD

**Issue by rlaehddls9** [ApolloAuto/apollo#13839]
System information
OS Platform and Distribution: Linux Ubuntu 18.04
Apollo installed from: Source
Apollo version: 6.0 

cyber_launch start /apollo/modules/perception/production/launch/perception_lidar.launch

I'm trying to run the perception module in Apollo with the data recorded directly with the cyber recorder, but can I run it only if I have an HD map? 

This is error message.
![image](https://user-images.githubusercontent.com/79086973/121011363-792cbf00-c7d1-11eb-9713-ad53ca43fdec.png)

**Comment by daohu527** [comment]
The error tells you that half the width of the road is 0.54m, normally it should not be less than 1.05m. The reason for this is because the width of the vehicle is generally more than 2m. It is recommended that you use other maps or correct this error.


It may work if you ignore this error, but there is no guarantee that other problems will occur

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
