### ISSUE TITLE
Perception module keeps turning off in Dreamview

### ISSUE THREAD

**Issue by krtt** [ApolloAuto/apollo#13872]
When I follow the tutorial [here](https://www.svlsimulator.com/docs/system-under-test/apollo5-0-instructions/) to run Apollo 5 with the SVL sim, after starting Apollo Dreamview and turning on the perception module, it turns off automatically in ca 2-6 seconds.

1. To start Apollo, follow the tutorial [here](https://www.svlsimulator.com/docs/system-under-test/apollo5-0-instructions/)
2. After reaching the step where you open Dreamview and turn on the perception module, observe it turn off by itself.

I expect it to stay on after I turn it on. Or notify me with a clear (error) message if something is wrong.

Screenshot:

![image](https://user-images.githubusercontent.com/22684441/122831850-23890400-d2f3-11eb-83eb-7e6d4d0bb269.png)

Perception log from /data/log:

```Log file created at: 2021/06/22 00:17:41
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0622 00:17:41.203817  9916 class_loader_utility.h:79] registerclass:MotionService,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so
I0622 00:17:41.212216  9916 class_loader_utility.h:79] registerclass:FusionCameraDetectionComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so
I0622 00:17:41.212285  9916 class_loader_utility.h:79] registerclass:MotionService,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so
I0622 00:17:41.212306  9916 class_loader_utility.h:79] registerclass:LaneDetectionComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so
I0622 00:17:41.212359  9916 class_loader_utility.h:79] registerclass:TrafficLightsPerceptionComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so
I0622 00:17:41.224659  9916 trafficlights_perception_component.cc:139] tl_tf2_frame_id: world tl_tf2_child_frame_id: novatel tf2_buff_size: 0.01
I0622 00:17:41.224740  9916 trafficlights_perception_component.cc:156]  _image_timestamp_offset: 0
I0622 00:17:41.224747  9916 trafficlights_perception_component.cc:160] _proc_interval_seconds: 0.125
```

**Desktop:**
 - OS: Kubuntu 18.04
 - Browser Firefox 89.0.1

**Comment by daohu527** [comment]
For now I don't know where the problem is. Could you pls provide more information?

Confirm whether there is a core_dump in `data/core` or check the log in `main_board.INFO`

**Comment by roshambo919** [comment]
I have a similar issue and cannot figure out why. Could it possibly be due to GPU out of memory? I notice that, before I enable perception, I'm close to the max GPU memory. 
(this is the same modules enabled as above, with perception and traffic light not enabled)
![image](https://user-images.githubusercontent.com/20426598/131415162-3a490a46-51ef-4e16-84c2-869578cd44f3.png)

Then, I enable perception. Checking `nvidia-smi`, I notice that I very briefly get an uptake in GPU memory while a process "mainboard" spins up.
![image](https://user-images.githubusercontent.com/20426598/131415410-8040aa76-b2b4-487e-bb4d-8efbf86ba594.png)

Then the perception automatically toggles off, and the mainboard process disappears...don't see anything suspicious in the log either.

**Comment by roshambo919** [comment]
Notably, I'm able to get "traffic light" to be enabled for longer, but sometimes all of the sudden it will turn off automatically.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
