### ISSUE TITLE
Where is the Dreamview UI file? 

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#13892]
System information
Ubuntu 20.04 
Apollo version 6.0
Hi, I'm looking for the dreamview UI file. I believe I have found it but I just want to be sure it is the correct file. Can someone provide me with the file name and path that has the UI and UX of dreamview so I can confirm? Thank you.

**Comment by DrShIkIgAmy** [comment]
Hi, it's not qt app to have ui file. DreamView is the react based single page web app, so it has backend and frontend parts. I believe you are curious in front-end, so you may check  apollo/modules/dreamview/frontend/src. In this directory you can find react components under folder components. Keep in mind, that you are to install npm modules and build whole project (not apollo.sh build) in order to make any changes in UI

**Comment by jp12AI** [comment]
ok, thank you for the information. I'll look there. Closing the issue
