### ISSUE TITLE
Multithreaded modules

### ISSUE THREAD

**Issue by thymbahutymba** [ApolloAuto/apollo#13940]
Hi guys, I'm inspecting the code and I've been wondering whether a module is multi-thread (multi-process) or not. I was able to figure out that the prediction module exploits a threadpool, therefore it should be multi-thread. What about control, planning and so on and so forth? Some tips on how to figure it out? Thanks in advance.

**Comment by daohu527** [comment]
In short, a simple module is single threaded. 

Because the code usually create a thread through `new thread()`, and there is no unified configuration, it can only be viewed through the code

multi-thread : perception, planning, canbus
single-thread: control, localization

## process and thread
And be careful to distinguish between threads and processes. 
1. cyber_launch will create a process
2. dag file will create some threads

**Comment by thymbahutymba** [comment]
Thanks for the reply. So I was not able to find out where planning create new threads. I would like to go deeper in order to better understand how those modules work. I also saw that cyber_launch create a new process (mainboard) which, as you said, create some threads, how many threads? How can I inspect all of this stuff? Thanks again.

**Comment by daohu527** [comment]
There are ways to count, the easiest way is to view threads by `ps -ef | grep xxx`.

If you require analysis from the code, you can take attention in `cyber::Async` or `new std::thread`. In fact, Cyber automatically schedules system processes. But some modules will also create threads by themselves, which is not recommended.

You can find some `new std::thread` in module, actually I think `cyber::Async` is better. 

If you want to really understand these in depth, you need to understand cyber scheduling then.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
