### ISSUE TITLE
How To put the car in a Correct city Position on Dreaview: Car is lost..

### ISSUE THREAD

**Issue by marcusvinicius178** [ApolloAuto/apollo#13971]
Hi my system info is below:

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
-  Ubuntu 18.04
- **Apollo installed from (source or binary)**:
- Docker - Git clone
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- Version 5.0
- **Output of `apollo.sh config` if on `master` branch**:
- I am on Master branch

### Steps to reproduce the issue:
Hi I have runned the 
`./scripts/bootstrap.sh`

And set differenti cities on Dreamview! However in all the cities the vehicle is not put in good coordinates, near the highway. And the vehicle is totally lost. How to put in a position in the beginning of the road?

Is there a tutorial for that?

### Supporting materials (screenshots, command lines, code/script snippets):

The vehicle is totally lost:

![image](https://user-images.githubusercontent.com/43826438/126853222-c1765f3c-80e1-40cd-a242-3709f1b9f074.png)

The most close from the road the car can reach is in San Mateo City. But It is also too far...

![how_to_position_right](https://user-images.githubusercontent.com/43826438/126853192-f1df9da2-0613-4661-b910-7c2f7e27fbca.png)

**Comment by daohu527** [comment]
You can select the starting point and ending point on routing, and the starting point you set is the starting point of the car.

**Comment by marcusvinicius178** [comment]
Humm, but on Dreamview in Route Editing tab there is not this option...

I created then a Default Routing from point A (start) to Point (B)

![image](https://user-images.githubusercontent.com/43826438/127680104-6dac5bc8-01d3-4920-9849-5dc15d5f5e0d.png)

And then I pressed the button send, but the car didn't start the cycle...

Another attempt was change the start position (x,y) from routing_map.txt and sim_map.txt files to the position I wish the car starts, I have rebuilt Apollo...but the car does not get this position, but the old one. 


![image](https://user-images.githubusercontent.com/43826438/127679771-0d3b2026-383f-4458-bcef-a83f435758b4.png)

**Comment by daohu527** [comment]
Click 2 points with the mouse, you can see 2 red circles, and then send the routing command

**Comment by marcusvinicius178** [comment]
No no I don't wish to send the car to a goal spot. 
I wish that the car be spawned into a different start position.
I have already used sim control to create several numbers of red circle points and send the car to reach these points, but this is not the point.

**Comment by daohu527** [comment]
do you really try it, I tried version 5.0 and it works well. If you choose 2 points then the first point is the starting point of the car

**Comment by marcusvinicius178** [comment]
Yes But I am using Apollo 6.0, once it was easier to extract Cyber channels data using the Python interface. maybe this be the reason....
Is not another way of changing the coordinates on the text files, in such way that it puts the car in another start position? I changed those files, built them, however the car didn't update the start position

**Comment by daohu527** [comment]
6.0 is also work.
1. routing_map.txt is a map for routing, which is a map
2. sim_map.txt is a map for dreamview display usage

I provided a method every time, but you gave up after trying it, and you tried other methods without knowing the principle.
You don’t try to look at the code, so I don’t know if it’s because the deadline limits your thinking, or because you’ve been working this way.

## solution
Frankly speaking, I have had this problem more or less before, but this method is not conducive to solving the problem. Similar to athletes, try to reduce unnecessary movements and concentrate on the moment.

So we are back to your question, you can try to add 2 points with the mouse in routing, and then send routing. Of course, I don't know if you have opened the routing and planning modules after opening sim_control.
If these are all OK, when you send the routing command, the car will go from the starting point to the ending point you specified
