### ISSUE TITLE
build and run rtk localization seperately

### ISSUE THREAD

**Issue by AM055** [ApolloAuto/apollo#14019]
### System information
- **OS Platform and Distribution*: Linux Ubuntu 18.04
- **Apollo installed from*: source 
- **Apollo version: master

### Steps to reproduce the issue:
*** I want to test localization module seperately; I build rtk localization and needed dependencies.
*** My question : Since I don't have the required hardware, 
can I use txt files containing IMU and GPS information as input to the localization module? 
***when I tried to do this I failed to generate the needed messages.

**Comment by AMEKNI** [comment]
some on can help me?
I can test rtk localization witn demo record and it work fine. But I want to use my txt files to generate topics!!

**Comment by AMEKNI** [comment]
zhouyao4321, liouyx ???? do you have any idea about my question?

**Comment by daohu527** [comment]
Simply put, you can create a cyber node, read the file, and publish the corresponding topic.

## steps
1. create a cyber node
2. read the gps and imu message from file
3. publish the topic

**Comment by AMEKNI** [comment]
Hi, thank you for your  response. I think I did that but since I obtainted this as output of cyber_monitor (image below); all channels but no data flow through channels! so somthing is wrong.
1. create a cyber node: OK
2. *******read the gps and imu message from file : Can you please give me additional information for this step, more détails!!!!!!!!!*******
3. publish the topic: OK

![image](https://user-images.githubusercontent.com/87365572/129474197-676ef7c7-f3b3-4ea4-820b-da350779d3f1.png)

**Comment by daohu527** [comment]
you can ref to [control_tester](https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/control/tools/control_tester.cc), It reads the message from the file and publishes it

**Comment by AM055** [comment]
Hi, I want to test localization individually! why should I refer to control model.?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
