### ISSUE TITLE
how to convert .record file to rosbag .bag file

### ISSUE THREAD

**Issue by ryanncheng** [ApolloAuto/apollo#14113]
I have some .record data , now i want to test a program depends on ros, how can i convert .record file to .bag file?

**Comment by daohu527** [comment]
Sorry, it seems that there is no such tool at the moment, we have to write one maybe. : )

**Comment by jdcllh** [comment]
same situation…do you get any solution now?

**Comment by daohu527** [comment]
There is a python tool [cyber_record](https://github.com/daohu527/cyber_record) can read cyber record, and then use [rosbag](https://pypi.org/project/rosbags/) to write a bag.

You need to implement the function to convert the message from cyber to ros messages yourself, it shouldn't be difficult

Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
