### ISSUE TITLE
Using NVIDIA compute capability 8.6 GPU with Apollo 6.0

### ISSUE THREAD

**Issue by josh-wende** [ApolloAuto/apollo#14247]
Hi, I'm trying to build Apollo 6.0 to use with LGSVL simulator and my NVIDIA RTX 3090 GPU, but the build failed because compute capability 8.6 (which the 3090 is) is not supported. It is my understanding that Apollo has added support for CC 8.6 since the release of Apollo 6.0, is there a way to get this functionality in Apollo 6.0? I tried running `dev_start.sh --dist testing` but it did not recognize the `--dist` flag.

**Comment by L-Net-1992** [comment]
This problem is because your graphics card is relatively new and has high computing power. However, this problem has been solved in 7.0.0 Version . If you don't want to update the version, there are some ways to solve this problem.In this file（/home/lqs/apollo/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl）
You should comment out the two for loops and add a line of code:
**nvccopts += '-gencode=arch=compute_75,\"code=compute_75\" '**

**Comment by josh-wende** [comment]
Thanks, this worked!
