### ISSUE TITLE
LGSVL said 'sunset plan'

### ISSUE THREAD

**Issue by Linsha350** [ApolloAuto/apollo#14287]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hi.
Last week, LGSVL said 'Sunset Plan' to suspend development of SVL Simulator.
No fix, No Release.
In addition, the web user interface is running only until June 30, 2022.
After that time, SVL simulator is been running Offline, locally.
However, the local running is only from cache, and the users cannot change any other options.

So, it is evitable to find other simulator.

What is other simulator, which can be connected to Apollo Auto?

**Comment by ntutangyun** [comment]
I'm trying to set up a new repository accepting issues and pull requests from the community. 

https://github.com/SVL-simulator/simulator

The new repository is set to be community-driven.

If you still need to use the SVL simulator, you can. I'll find a time to modify the latest release and let it run in the standalone mode just like previous versions before the cloud service dependency. 

since the simulator is open source, you can always use the Unity editor to modify and update it on your own :) so there is basically no issue regarding your concern that "users cannot change any other options" :)
