### ISSUE TITLE
Cython package is not found to allow BUILD to complete successfully

### ISSUE THREAD

**Issue by JANE0015** [ApolloAuto/apollo#14415]
1. There is no cython file found in the GitHub but the error I have encountered is about no cython packages found in docker.
2. I have tried to download Cython packages locally and import it into the docker but the error is still no cython packages found. Meaning the docker could not read the packages from outside.

Kindly advise.
Thank you!

**Comment by JANE0015** [comment]
![error](https://user-images.githubusercontent.com/67865147/163299715-7c2a7e89-8e50-4f3a-aaa0-3693757a5248.jpg)

**Comment by Timothyoung97** [comment]
Hi @JANE0015 did you manage to resolve the issue? Would like to know more as I am facing the same issue.

**Comment by daohu527** [comment]
Are you compiling in a container, it is possible that other libraries depend on it and are downloaded over the network, make sure your network is ok

**Comment by Timothyoung97** [comment]
Hi, I resolved the issue recently. 

Well... I guess this is not exactly the right solution to the issue, but the problem is that I was building the project behind a proxy. There are some complications with building the project behind a proxy, where the docker daemon cannot pull the packages (maybe due to config or certification, etc).

I simply redirect the internet connection to my personal network and it works.
