### ISSUE TITLE
Direction attribute of lane tag does not work

### ISSUE THREAD

**Issue by metra4ok** [ApolloAuto/apollo#14521]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: official docker container
- **Apollo installed from (source or binary)**: source
- **Apollo version**: 7.0

### Issue:
In Apollo HD map documentation there is description of `direction` attribute of the `<lane>… <lane/>` tag:

> Name: direction
> Type: string
> Value: forward / backward / bidirection
> Description: Direction of the lane relative to the sequence of point set.

According to that information, I should use `direction="backward"` attribute to create a lane with a routing direction backward to its point set, but this does not work at all.

Why it does not work?
How the road with bi-directional lanes should be created?

Looks like the same problem was discussed in #5865, but there is no answer.

**Comment by daohu527** [comment]
In my opinion, all roads are forward, or some are bidirectional. I don't know any roads are used for backward.

In theory routing support for two-way lanes is simple, but planning requires some work.
Because the current lane lines are sampled into points, which contain the distance from the starting point, it is necessary to flip these data.

For now routing and planning does not support BIDIRECTION, we'll discuss whether to add this feature and add it to the to-do list.
