### ISSUE TITLE
which module post the /tf from novatel to world ？

### ISSUE THREAD

**Issue by InterKnight** [ApolloAuto/apollo#14575]
### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source )**:
- **Apollo version (7.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

Hi，thanks you for great project.

I'm wondering which module post the /tf from novatel to world ？

And why we need this tf?  because we have got tf (novatal to localization) and (localization to world)

**Comment by CesarLiu** [comment]
https://github.com/ApolloAuto/apollo/blob/12ab9e94891cfd2ef5a001f6e18bf56422402e42/modules/drivers/gnss/conf/gnss_conf.pb.txt#L42
it answers which module but doesn't answer why.
I guess, It could be relevant to the logic of apollo localization: if you can use rtk mode, then it can already publish the tf from world to novatel; if you don't use rtk, maybe the other localization module would publish world to localization? I'm just guessing! 
'"// Since "/tf" topic has dynamic updates of world->novatel and
  // world->localization, novatel->localization in tf buffer is being changed
  // and their transformation does not represent for static transform anymore."' A comment was found in the code.

**Comment by daohu527** [comment]
Yes you can get the coordinate transformation by the above 2 ways.  and /tf from novatel to world is publish by gnss driver.
