### ISSUE TITLE
Fake prediction does not enter Proc function

### ISSUE THREAD

**Issue by IvDmNe** [ApolloAuto/apollo#14755]
`linkstatic = False` in bazel BUILD files causes components based on TimerComponent to never enter Proc() function.

To reproduce:
1. Run Fake prediction module: `mainboard -d modules/tools/prediction/fake_prediction/fake_prediction.dag`
2. In cyber_monitor the chanel `/prediction/ostacles/` will be empty.

To avoid the bug:
1. chank static linking to True in this line:
https://github.com/ApolloAuto/apollo/blob/b00c030ac02c54f98579d3d3e879dbf52f0d1d53/modules/tools/prediction/fake_prediction/BUILD#L18

2. rebuild this package
3. the messages will appear.

Similarly, if you change linkstatic to False in modules such as Control or Monitor, they will stop execute Proc function.

Version:
This bug appeared only in Apollo 8.0. In Apollo 6.0 the modules without static linking work well. (didn't test in Apollo 7.0).

Do you have ideas why this happens?

**Comment by daohu527** [comment]
Yes, it's not a bug, this is due to 8.0 changing the compilation method.
- Before 8.0, each library is compiled as a dynamic library, and a module may have many dynamic libraries
- After 8.0, all library is compiled as a dynamic library, and then linked as one dynamic library

The advantage of this is that there is no need to package so many dynamic libraries when release, and it need a trick in bazel like use both `linkshared` and `linkstatic` to achieve this
```
cc_binary(
    name = "libcontrol_component.so",
    linkshared = True,
    linkstatic = True,
    deps = [":control_component_lib"],
)
```

**Comment by IvDmNe** [comment]
Does it mean that all binaries should be compiled with `linkstatic = True`? There are few such targets with False in prediction and planning modules. 

As I understand, this flag only defines a mode for linking libraries and is not supposed to brake modules. With `linkstatic = False` the Init() function of TimerComponent is executed but not the Proc() function. Or there are some other changes for new compilation method except of `linkstatic` flag?

**Comment by daohu527** [comment]
Yes, this a trick for bazel, but not highly recommended. Bazel recommends static links when publishing, but we publish so files.
