### ISSUE TITLE
Why changing .conf param value needs a re-build?

### ISSUE THREAD

**Issue by GiantSeaweed** [ApolloAuto/apollo#14778]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution: Linux Ubuntu 20.04**:
- **Apollo installed from : package**:
- **Apollo version: 8.0**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
I am following the steps of Apollo8.0 QuickStart at [here](https://github.com/ApolloAuto/apollo/blob/master/docs/02_Quick%20Start/apollo_8_0_quick_start.md#step-5-enter-sim-control-simulation-mode-for-debugging).
In Scenario2 Step5 Point6, I want to tune the `default_cruise_speed` at [here](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/conf/planning.conf#L4).

Directly reload the planning module on Dreamview or restart the dreamview via `aem bootstrap restart` do not work.
I am not clear why it requires a re-build (as the doc said `buildtool build --packages planning_customization`) for the changed `default_cruise_speed` to take effect. 
I thought planning.conf is a configuration file that will not affect compiled binary?

Can anyone explain about this? Did I misunderstand something?
 
Thanks in advance!

**Comment by WildBeast114514** [comment]
In apollo 8.0, there are actually two configuration files, one in the source code, i.e. the configuration file stored under /apollo_workspace, and the other one that is actually read by the binary, i.e. the configuration file stored under /apollo. 

When you change the configuration file under /apollo_workspace, the binary does not read the changes from /apollo, so they will not take effect.

To modify the configuration files, you can: 
1. recompile the module corresponding to the modified configuration file so that the configuration file under /apollo_workspace overwrites the configuration file under /apollo
2. or directly modifying the configuration under /apollo

**Comment by GiantSeaweed** [comment]
Hi @WildBeast114514 @daohu527 I got it and thank you very much for the help!
