### ISSUE TITLE
[Preception] Apollo 7.0 Close Perception module makes planning and prediction modules not working

### ISSUE THREAD

**Issue by Xuanye-Zhang** [ApolloAuto/apollo#14802]
Hi team,

I am using Apollo r7.0.0 to test vehicle crossover static NPC. Using perception module, the system works fine. 

But when I closes the perception module and want to use obstacle_gt to test the crossover, it makes planning and prediction module not working as below shows
![Screenshot from 2023-03-02 16-53-43](https://user-images.githubusercontent.com/83740261/222381819-b1539461-cf1f-47c9-95da-c453dfcdd70a.png)
![Screenshot from 2023-03-02 16-53-50](https://user-images.githubusercontent.com/83740261/222381837-d757b982-d93c-413b-81a4-d89839e9fa85.png)

And I tried to open the planning module manually but find with this error
E0302 16:53:17.438055 16491 reference_line_provider.cc:205] [planning]Routing is not ready.

![Screenshot from 2023-03-02 16-53-23](https://user-images.githubusercontent.com/83740261/222382221-b43f3b8b-f1da-42e6-b1fd-71fb87762489.png)
And the prediction and routing I thought was running.
![Screenshot from 2023-03-02 17-06-40](https://user-images.githubusercontent.com/83740261/222382672-6dc9921c-1a2e-4277-be45-295739734e2a.png)

And in the simulator, ground truth sensor works fine. The ground truth ID is e3fef197-9724-48ec-b98e-c5a0892d09c4.
![Screenshot from 2023-03-02 17-07-49](https://user-images.githubusercontent.com/83740261/222382943-06191cfa-ca40-4bf2-b9c1-84f721802530.png)
And the vehicle ID is 8e776f67-63d6-4fa3-8587-ad00a0b41034. Vehicle is for apollo 6.0.
![Screenshot from 2023-03-02 17-10-17](https://user-images.githubusercontent.com/83740261/222383558-b31c1c4c-a635-4f3a-a644-a1c432bde9ef.png)

Any advice on this problem?

**Comment by YuqiHuai** [comment]
@Xuanye-Zhang 
For the vehicle ID provided (8e776f67-63d6-4fa3-8587-ad00a0b41034), the 3D ground truth is publishing data to `/apollo/perception/obstacles_gt`, which might need to be changed to `/apollo/perception/obstacles` to get it working. You can modify the JSON file to make this change.

I might be wrong but the prediction module is probably triggered by perception messages and the planning module is probably triggered by prediction messages, which is why SimControl is publishing dummy perception messages by default.

I suggest you use vehicle `2e966a70-4a19-44b5-a5e7-64e00a7bc5de` provided by https://github.com/MingfeiCheng/AV-Fuzzer/ This vehicle ID has been working fine for me.

**Comment by Xuanye-Zhang** [comment]
> @Xuanye-Zhang For the vehicle ID provided (8e776f67-63d6-4fa3-8587-ad00a0b41034), the 3D ground truth is publishing data to `/apollo/perception/obstacles_gt`, which might need to be changed to `/apollo/perception/obstacles` to get it working. You can modify the JSON file to make this change.
> 
> I might be wrong but the prediction module is probably triggered by perception messages and the planning module is probably triggered by prediction messages, which is why SimControl is publishing dummy perception messages by default.
> 
> I suggest you use vehicle `2e966a70-4a19-44b5-a5e7-64e00a7bc5de` provided by https://github.com/MingfeiCheng/AV-Fuzzer/ This vehicle ID has been working fine for me.

Thanks! it works!
The issue is when using only 3D ground truth have to publish the 3D ground truth sensor message in  `/apollo/perception/obstacles` instead of  `/apollo/perception/obstacles_gt`.
