### ISSUE TITLE
Files in the code that could not be found

### ISSUE THREAD

**Issue by kathy-lee** [ApolloAuto/apollo#14864]
Hi, I'm a beginner at learning Apollo and am trying to run through the two demos as following:

- how to add a new lidar detector from docs at [https://github.com/ApolloAuto/apollo/blob/master/docs/06_Perception/how_to_add_a_new_lidar_detector_algorithm.md](url). In the file 
- how to replace a lidar detector model from docs at [https://github.com/ApolloAuto/apollo/blob/master/docs/02_Quick%20Start/apollo_8_0_quick_start.md#step-7-model-replacement](url)

But I have two questions could not figure out, could someone help me please? Many thanks!

In the last step of the 1st demo, it says needs to change the value of "detector" to the new detector in "file lidar_obstacle_detection.conf" located in corresponding sensor folder in "modules/perception/production/data/perception/lidar/models/lidar_obstacle_pipline" . But in the 2nd demo, it says needs to change the following config items in file "modules/perception/pipeline/config/lidar_detection_pipeline.pb.txt", follwoing is how it looks in the current master branch. But the last three files in "cnnseg_config" section don't exist anymore, how can it work? Next question is, why the ways to change a detector in these two demos are different? As my understanding, both of them need to make the detector change work. But these two demos are changing different files to make it work.

```
stage_config: {
  stage_type: CNN_SEGMENTATION
  enabled: true

  cnnseg_config: {
    sensor_name: "velodyne128"
    param_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_param.conf"
    proto_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/deploy.prototxt"
    weight_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/deploy.caffemodel"
    engine_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/engine.conf"
  }
}
```

**Comment by qilinhu** [comment]
@kathy-lee Hi！
For your first question，some time ago, we upgraded the perception. Users can deploy a clearer and simpler deployment model according to the pipeline, so you can deploy according to the 2nd demo.The two methods will read different configuration files.
For your second question, in order to reduce the size of the code base, we removed the model files from the code base. Now you can download the required model files through the amodel tool, and the downloaded model files will be installed in the corresponding path.
Hope to help you！
