### ISSUE TITLE
why borrowing lane is not necessary when referencelines is not single in the lane borrow task of planning

### ISSUE THREAD

**Issue by benlvzi** [ApolloAuto/apollo#15118]
In my view,
the check is not reasonable, 
but  borrowing lane is not necessary when referencelines is single , ok?

the original code as follow:
` // ADC requirements check for lane-borrowing:
  if (!HasSingleReferenceLine(frame)) {
    return false;
  }
` 
in my opinion:
` // ADC requirements check for lane-borrowing:
  if ( HasSingleReferenceLine(frame)) {
    return false;
  }
`

**Comment by ycraurora** [comment]
There will be more than one reference line only when the start point is not in the same passage with the end point, which means ego should change lane. And apollo tends to disable lane borrow in lane change scene for now. So that's why lane borrow is not necessary when HasSingleReferenceLine is false.
But actually ego should be able to perform lane-borrow when there are more than one reference line. Check the TODO here: 
https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/modules/planning/tasks/deciders/path_lane_borrow_decider/path_lane_borrow_decider.cc#L134C3-L139C3

**Comment by benlvzi** [comment]
I got it , thank you very much for your help.
