### ISSUE TITLE
Gnss  | Open device /dev/ttyS0 failed, error: Permission denied

### ISSUE THREAD

**Issue by yooyo-Q** [ApolloAuto/apollo#15570]
### System information

- **Ubuntu 20.04**:
- **Apollo installed from docker**:
- **Apollo version (9.0)**:

### Steps to reproduce the issue:
`cyber_launch start modules/drivers/gnss/launch/gnss.launch`

output:
![image](https://github.com/user-attachments/assets/4c644988-b48b-4f88-82ec-c02c181a4923)

"Execute `chmod 777 /dev/ttyS0`"
![image](https://github.com/user-attachments/assets/dde583b6-6f13-4edb-9dec-a3a2d1aac7b3)

"When I change the permissions of /dev/ttyS0 to 777, the device can be read correctly. However, every time I restart the server, the permissions revert back to their original state, requiring me to reconfigure them. I would like to know if this is a feature of Apollo or a bug."

**Comment by daohu527** [comment]
In Linux, setting the permissions of the device file `/dev/ttyS0` to `777` might reset after each reboot. This is usually because device files are dynamically created during the boot process, and their permissions are managed by the `udev` device manager. Here are possible reasons and solutions:

### 1. `udev` Rules Configuration
`udev` dynamically manages device nodes according to system rules, including setting permissions. Each time the system starts, `udev` re-creates the device nodes based on these rules, overriding any manual permission changes.

#### Solution
You can create a custom `udev` rule in the `/etc/udev/rules.d/` directory to persist permission settings.

1. **Create a custom rule file**  
   Create a new rule file, such as `99-ttyS0.rules`:
   ```bash
   sudo nano /etc/udev/rules.d/99-ttyS0.rules
   ```
2. **Add the rule**  
   In the file, add the following content, setting `MODE` to the desired permission (e.g., `777`):
   ```plaintext
   KERNEL=="ttyS0", MODE="0777"
   ```
3. **Reload `udev` rules**  
   After saving the file, reload the `udev` rules with the following commands:
   ```bash
   sudo udevadm control --reload-rules
   sudo udevadm trigger
   ```

**Comment by yooyo-Q** [comment]
Thank you so much
