### ISSUE TITLE
Are there any document about control module?

### ISSUE THREAD

**Issue by Wsine** [ApolloAuto/apollo#1974]
there are too many code about control module, and it seems there are several times bug fix about control part. so can you please some documentations to help to review the control module, cause it is the safe guarantee part of the system.

**Comment by Capri2014** [comment]
@Wsine There are a few documents related to control under https://github.com/ApolloAuto/apollo/tree/master/docs/howto 

Also the default lat + lon controllers have more than thousands of  hours of test on it and even on different vehicle platforms and are quite reliable under different driving scenarios. 

The fix is mainly for MPC controller. Which is by default turned off and the internal version of it has also been tested for hundreds of hours as well.

**Comment by Wsine** [comment]
thanks @Capri2014 . I am writing a control algorithm, so i take apollo control algorithm as references. thanks for answering.

**Comment by Capri2014** [comment]
cool @Wsine please keep us posted. :)
