### ISSUE TITLE
Read code from ṕerception/obstacle/fusion

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#2515]
Hi all,

Iḿ reading perception/obstacle/fusion source code.

without any documentation, I barely understand the loops&fuctions, anyone can share some ideas?

Or provide your contact here so we can discuss :)

**Comment by kechxu** [comment]
Hello,

You may checkout some useful documents here
https://github.com/ApolloAuto/apollo/tree/master/docs/specs

For perception, you can read these ones:
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception.md
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/traffic_light.md
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/lidar_calibration.pdf

Thanks

**Comment by yuan-ji** [comment]
hi, maybe we can disguess it with  each other. I‘ll implemant a blog to describe the fusion part in two weeks.

**Comment by JonathanJones92** [comment]
You can provide your contact here

**Comment by yuan-ji** [comment]
is.yuan.ji@gmail.com This is my email address. Could you please send me
your wechat nummber by email? I don't think it's a good ideal to leave the
wechat hier directly.

2018-02-03 21:29 GMT+08:00 Jonathan Jones <notifications@github.com>:

**Comment by Zhenni17** [comment]
Hi @yuan-ji,

My name is Zhenni, and I am the community manager for Apollo Project. I want to follow up with you because you mentioned that you are working on a blog about perception module. I would love to connect with you to see if there is any support we can provide you. Or we can promote your blog on our official channels. Please feel free to send me an email to connect with me at: wuzhenni01@baidu.com.

Looking forward to hearing back from you!

Best,
Zhenni

**Comment by Zhenni17** [comment]
Hi @JonathanJones92,

We are working on some tutorials, blog articles that will focus on perception aim to help our developers like you. We would love to learn more about what are some of your specific questions so that we can incorporate them into our materials. Btw, are you working on any autonomous driving project? Feel free to send me an email to connect with me at wuzhenni01@baidu.com.

Best,
Zhenni

**Comment by techoe** [comment]
We have all documents in .md files explaining algorithm. We will have free Udacity class to explain further about each module. Thank you!
