### ISSUE TITLE
Adding a vehicle that doesn't use the canbus to control steering, braking, throttle

### ISSUE THREAD

**Issue by popeyedpanther** [ApolloAuto/apollo#2913]
Hello,

I am trying to add a new vehicle to apollo but the vehicle I am using does not use the canbus to control the vehicle. It has physical actuators connected through serial.  Any tips on how to implement this into the apollo framework as best as possible? Is there any code already implemented for reading/writing serial in apollo?

Thanks
(I'm a little slow on the OOP approach)

**Comment by Capri2014** [comment]
@popeyedpanther  Sorry for the late reply. The easiest way would be to add a driver under modules/drivers/ that supports serial communication instead of using the ESD can or linux can interface we provide. A good sample code is : http://www.raviyp.com/embedded/189-serial-port-programming-in-linux-using-c-working-code. The implementation should be quick similar to https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc through the data structure & detailed API are not exactly the same.

**Comment by Capri2014** [comment]
@popeyedpanther Another good lib that I forgot to mention https://github.com/ros-drivers/rosserial

**Comment by popeyedpanther** [comment]
Thanks for the reply. Ill try it out. The actuators are Animatics SmartMotors. I don't think I will be able to get ROS serial working on their hardware.
