### ISSUE TITLE
why don`t  HMI dreamview  show the road info ?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#295]
it has just a trjactory bu no road ,no lane. we can not tell is the trajectory is right~

**Comment by jinghaomiao** [comment]
Apollo 1.0 supports RTK which does not rely on the map. 

Map will be supported in Apollo 1.5 which will be released in late Sept 2017.

**Comment by westeast** [comment]
thanks for your answer~

**Comment by Eddy-W** [comment]
I have built apollo v1.5 successfully. But when I ran the command
```bash
rosbag play ./docs/demo_guide/demo_1.5.bag --loop
```
There were still no road or no lane in the Dreamview as the figure shows below, rather than the [dv_trajectory_1.5.png](https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/images/dv_trajectory_1.5.png) that we expect to show all information including traffic lanes and signals.
Did I play a wrong bag file or run a wrong command?
![](https://user-images.githubusercontent.com/7567546/30789858-f8636dd0-a1da-11e7-83af-86d08fb691c3.png)
