### ISSUE TITLE
Question: How does apollo figure out absolute path for config files?

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#3040]
I am trying to run canbus from command line as the following:

```
# export APOLLO_ROOT_DIR=/apollo
# canbus --flagfile=/apollo/modules/canbus/conf/canbus.conf --log_dir=/apollo/data/log
modules/common/data/global_flagfile.txt: No such file or directory
```
For instance, here is the code to define FLAGS_canbus_adapter_config_filename:

```
DEFINE_string(canbus_adapter_config_filename,
              "modules/canbus/conf/adapter.conf", "The adapter config file");
```

How does "/apollo" get prepended to the relative path? A more general question: how does apollo figure out the absolute path for those config files? Which environment variables are needed?

**Comment by xiaoxq** [comment]
In the past we generally assume that the PWD is always the apollo root, so we define the paths as relative path. Recently we are trying to change them to absolute path because docker container is independent with users' host environment.

To make it simple, you can change the flag to "/apollo/modules/...".

**Comment by jilinzhou** [comment]
Thanks!
