### ISSUE TITLE
[Question]obstacles recognise issue by cloud points of perception module

### ISSUE THREAD

**Issue by chucklqsun** [ApolloAuto/apollo#3341]
Hi,

I added 1000 random points (outside ROI) into a pcd and the offline perception tool miss 3 obstacles in front of the vehicle. Is the algorithm or model behind the obstacle recognition by cloud points vulnerable to noise attack (points outside ROI)? My apollo code is checked out on the Jan 31, 2018.

This is original pcd.
![2891_wo](https://user-images.githubusercontent.com/15841738/37249721-ce2a0d3c-2540-11e8-9867-d71ce9767974.png)

[2891_original.zip](https://github.com/ApolloAuto/apollo/files/1800040/2891_original.zip)

This is pcd with 1000 random noise points ouside ROI
![2891_wi](https://user-images.githubusercontent.com/15841738/37249729-f8d0f406-2540-11e8-86db-b19c986bce12.png)

[2891_wi_1k_random.zip](https://github.com/ApolloAuto/apollo/files/1800041/2891_wi_1k_random.zip)

[pose.zip](https://github.com/ApolloAuto/apollo/files/1800042/pose.zip)
Position in sunnyvale_loop map
![map_2891](https://user-images.githubusercontent.com/15841738/37249764-bc6ea926-2541-11e8-85c1-633104e1ad94.png)

Regards,
Liqun Sun

**Comment by weidezhang** [comment]
thanks for the post. since cnn seg is deep learning trained, it might happen if you add noise point into the data itself. in practise, there could be multiple pipeline doing segmentation based on traditional method as well as deep learning method. Also, for cases like that, models can be fine tuned using data augmentation.
