### ISSUE TITLE
Question about control conf

### ISSUE THREAD

**Issue by silverland79** [ApolloAuto/apollo#3515]
hi:
I have some question about module of control,lincoln.pb.txt.
What are the preview_window's parameters  like cf,cr,mass_fl... ?
Please explain the meaning of these parameters,thank you very much.
lat_controller_conf {
  ts: 0.01
  preview_window: 0
  cf: 155494.663
  cr: 155494.663
  wheelbase: 2.85
  mass_fl: 520
  mass_fr: 520
  mass_rl: 520
  mass_rr: 520
  eps: 0.01
  matrix_q: 0.05
  matrix_q: 0.0
  matrix_q: 1.0
  matrix_q: 0.0
  cutoff_freq: 10
  mean_filter_window_size: 10
  steer_transmission_ratio: 16
  steer_single_direction_max_degree: 470
  max_iteration: 150
}
lon_controller_conf {
  ts: 0.01
  brake_deadzone: 15.5
  throttle_deadzone: 18.0
  speed_controller_input_limit: 2.0
  station_error_limit: 2.0
  preview_window: 20.0
  standstill_acceleration: -3.0
  station_pid_conf {
    integrator_enable: false
    integrator_saturation_level: 0.3
    kp: 0.2
    ki: 0.0
    kd: 0.0
  }

**Comment by berthu** [comment]
These are parameters for the bicycle model of lateral vehicle dynamics, a common dynamic model used for lateral vehicle control, and a model used by the lateral controllers to predict vehicle steering dynamics. You can learn more about it in "Vehicle Dynamics and Control" by Rajesh Rajamani. The parameters cf and cr are cornering stiffness parameter estimates for the front and rear axle tires. The mass parameters are vehicle mass estimates on each tire. They are separated in order to estimate the inertia moment of the vehicle. Preview window is a more complicated parameter; I believe it is for adjusting an overshooting problem in LQR controllers, using a technique called "Optimal Preview Control".

**Comment by silverland79** [comment]
Thank you very much.
