### ISSUE TITLE
MPC _controller  model

### ISSUE THREAD

**Issue by ydl1986** [ApolloAuto/apollo#3641]
can you  share the model  which is used in  MPC _controller
(about station_error、speed_error  )

**Comment by gengqx** [comment]
The model Apollo used is Bicycle model，It could be found in the book ----vehicle Control and dynamics 2012.

**Comment by slivingston** [comment]
@gengqx where in the source code is the model?

**Comment by slivingston** [comment]
I did not find an explicit comment in the documentation about it being bicycle model, but the bicycle model is consistent with the implementation in [modules/control/controller/mpc_controller.h](https://github.com/ApolloAuto/apollo/blob/b094cd655d61cb8b349d8c48b2c3b42e14ae2d3a/modules/control/controller/mpc_controller.h) and [mpc_controller.cc](https://github.com/ApolloAuto/apollo/blob/b094cd655d61cb8b349d8c48b2c3b42e14ae2d3a/modules/control/controller/mpc_controller.cc), and the parameters in [lincoln.pb.txt](https://github.com/ApolloAuto/apollo/blob/b094cd655d61cb8b349d8c48b2c3b42e14ae2d3a/modules/control/conf/lincoln.pb.txt)

**Comment by slivingston** [comment]
@ydl1986 the station error and speed error updates are on [lines 602-603](https://github.com/ApolloAuto/apollo/blob/b094cd655d61cb8b349d8c48b2c3b42e14ae2d3a/modules/control/controller/mpc_controller.cc#L602-L603) of mpc_controller.cc

**Comment by 378281820qq** [comment]
@gengqx  @slivingston  Thank you for your answer. It's very useful. 
The  state equation of lateral_error/lateral_error_rate/heading_error/heading_error_rate  ,I can  find in the book ----vehicle Control and dynamics 2012。
But  I can't understand station_error/speed_error, can you give me the  state equation of station_error/speed_error ?

**Comment by 378281820qq** [comment]
@xiaoxq @Capri2014

**Comment by gengqx** [comment]
In Chinese，it would be easy for you to find the material.位置环，速度环，电流环。车辆控制没有电流环但是有加速度环。

**Comment by ydl1986** [comment]
@gengqx   能加你微信不？

**Comment by ydl1986** [comment]
@gengqx   谢谢您的回答

**Comment by Capri2014** [comment]
@gengqx Thanks for the help. The statement should was most right. In English , it would have station-loop, velocity-loop, acceleration-loop ( open-loop).  -- This is depending on the lower layer interface between control and chassis by wire system. @ydl1986

**Comment by canxinyinxue** [comment]
@gengqx  station_error是纵向位置误差么？ 为什么状态转移矩阵matrix_a_中，是matrix_a_(4, 4) = 1.0，而不是matrix_a_(4, 5) = 1.0，位置误差的导数不应该是速度误差么

**Comment by gengqx** [comment]
@canxinyinxue  由于在选择状态x的时候，把x选择成了6X1的，station_error是纵向位置误差，但是station_error rate 等于当前速度，而不是等于速度误差，所以我觉得matrix_a_鉴于当前的情况，怎么写都是不太符合实际的。

**Comment by Capri2014** [comment]
@canxinyinxue This actually should be matrix_a_(4, 5) = 1.0 instead, you are right. Thanks for pointing this out.

**Comment by gengqx** [comment]
@Capri2014 I don't think you are right,we all know that  the station_errror rate should be equal to the velocity not the velocity error.To fix that we could add another state.

**Comment by gengqx** [comment]
@Capri2014 Yeah ,Consider the reference point is a realative motion,You Are Right.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be fixed.

**Comment by Xiaodaxia2015** [comment]
I have some question about the dynamic model eqation, the 
\dot{speed_error} = -a*dt + \dot{\varphi}
where a is the control input a, and \varphi is the heading error rate.
I can't understand the equation. Please help me to figure it out 
the flowing is about the matrix_c_ and matrix_cd_

`  matrix_c_ = Matrix::Zero(basic_state_size_, 1);
  matrix_c_(5, 0) = 1.0;
matrix_c_(1, 0) = (lr_ * cr_ - lf_ * cf_) / mass_ / v - v;
  matrix_c_(3, 0) = -(lf_ * lf_ * cf_ + lr_ * lr_ * cr_) / iz_ / v;
  matrix_cd_ = matrix_c_ * debug->heading_error_rate() * ts_;`

**Comment by natashadsouza** [comment]
@JasonXu12 can you help with this?

**Comment by Shaquille-Wu** [comment]
请教老师一个问题
 按照书上（vehicel_dynamic_and_control）的公式： 
lateral_err_dot = Vy + Vx*(theta-ref_theta) 
但是apollo给的公式是：lateral_error_dot = linear_v * std::sin(heading_error) 
大佬能不能解释一下apollo为什么这么干的，希望老师给告知相关的原理和出处

**Comment by kevin-y-wang** [comment]
@Shaquille-Wu

**Comment by kevin-y-wang** [comment]
@Shaquille-Wu 
About your question, the answer is, this is actually  a compromise for the control implementation in the real road-test environment. 
The classic textbook give the theoretically-correct equation  lateral_err_dot = Vy + Vx*(theta-ref_theta); however, in the road-test environment, it is difficult for our sensors to measure the Vy (which is sliding speed of the car along the lateral y-axis), our localization module usually measure the "car speed" linear_v along the real heading direction, which is a combined moving speed of the car. In other words, linear_v is actually the combination of the v_longitudinal along the x-axis, and v_lateral along the y-axis  (here v_lateral = Vy + Vx*(theta-ref_theta). Since the direction of linear_v is the real heading direction of the car, then the angle between linear_v and x-axis (reference heading direction) should be "heading error".
So, v_lateral = lateral_error_dot = linear_v * std::sin(heading_error); 
With the same reason, if you review the lon_controller.cc, you will find that the v_longitudinal is defined as: 
double lon_speed = vehicle_state->linear_velocity() * std::cos(heading_error);
Hopefully these explanations answer your initial question.

**Comment by Shaquille-Wu** [comment]
thanks for you details!----- 原始邮件 -----发件人：Yu Wang<notifications@github.com>发送时间：2020-07-09 17:32:30收件人：ApolloAuto/apollo<apollo@noreply.github.com>抄送：Shaquille.Wu<icework@sohu.com>;Mention<mention@noreply.github.com>主 题：Re: [ApolloAuto/apollo] MPC _controller  model (#3641)
@Shaquille-WuAbout your question, the answer is, this is actually a compromise for the control implementation in the real road-test environment.The classic textbook give the theoretically-correct equation lateral_err_dot = Vy + Vx*(theta-ref_theta); however, in the road-test environment, it is difficult for our sensors to measure the Vy (which is sliding speed of the car along the lateral y-axis), our localization module usually measure the "car speed" linear_v along the real heading direction, which is a combined moving speed of the car. In other words, linear_v is actually the combination of the v_longitudinal along the x-axis, and v_lateral along the y-axis (here v_lateral = Vy + Vx*(theta-ref_theta). Since the direction of linear_v is the real heading direction of the car, then the angle between linear_v and x-axis (reference heading direction) should be "heading error".So, v_lateral = lateral_error_dot = linear_v * std::sin(heading_error);With the same reason, if you review the lon_controller.cc, you will find that the v_longitudinal is defined as:double lon_speed = vehicle_state->linear_velocity() * std::cos(heading_error);Hopefully these explanations answer your initial question.

**Comment by kevin-y-wang** [comment]
Hi, @Shaquille-Wu thanks for your interests and contributions to improve the Apollo platform. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer teams are more than happy to help that.

Thank you for supporting Apollo!
