### ISSUE TITLE
Apollo and software development process

### ISSUE THREAD

**Issue by ubercool2** [ApolloAuto/apollo#3820]
Hi, I have couple of questions with respect to Apollo SW development process. Having well defined and followed SW development process is the key to safety and possible certification.

1. Requirements. These can be high and low level and serve as an input to trace an intended feature development to its implementation and testing. I do not see them. For automotive standards such as ISO26262 this is a must.
2. Use case(s) define in which context the SW is to be used. E.g. car performing a maneuver through a 4 way stop. I also didn’t find any use case.
3. Code reviews. Are there any guidelines on how many people should review a particular pull request and what should they focus on? E.g. algorithm, style, …
4. Testing. I see quite some tests written in Apollo. But do you have an idea how much of code is tested and untested? I see that you write unit and integration tests. It would be great if you would use a code coverage tool (e.g. gcov/lcov) and display unit test coverage and integration test coverage.
5. Testing2. Do you run any SIL, HIL, torture or burn-in tests? Having coverage for those would also be great.
6. Linting. I see some mentioning of linters but couldn’t quite figure it out which ones do you use. Do you use static code analysers such as e.g. klockworks?
7. Design articles - I saw some how-tos but they do not seem to be explicitly linked to code. Design articles explains how a particular feature is to be used and what e.g. its limitations are.
8. Builds. I see that you have travis server that builds PRs.

There is much more checks to be applied if the code is to be automotive grade (e.g. MISRA compliance, MCDC code coverage, signed builds, etc..) but above is the bare minimum.

**Comment by lianglia-apollo** [comment]
A excerpt from "An Analysis of ISO 26262: Using Machine Learning Safely in Automotive Software":
---- ISO 26262 mandates the use of many specific techniques for various stages of the software development lifecycle. Our analysis shows that while some of these remain applicable to ML components and others could readily be adapted, many remain that are specifically biased toward the assumption that code is implemented using an imperative programming language. In order to remove this bias, we recommend that the requirements be expressed in terms of the intent and maturity of the techniques rather than their specific details.

**Comment by Peter9606** [comment]
well good questions

**Comment by Zhenni17** [comment]
Hi @ubercool2 , thank you for taking the time to explore Apollo and draft these questions for us. I would like to apologize that we did not get back to your questions sooner. These are all great questions and I will try to answer them individually:

1.    The autonomous driving industry is continually evolving and if you have followed Apollo throughout, you will know that we release newer versions continuously. Our new ReadMe has a high-level description of the system and sensor requirements with both the Hardware and Software installation guides exploring these requirements in detail. If you have more specific questions about what requirements you are looking for, please let us know. 
2.    Could you provide a more specific explanation of what you are looking for? If you are talking about where you can test the driving scenarios, our simulation platform has hundreds of use-cases which you could explore once you have set-up the platform. Let me know if you need help to get that started. If you have suggestions on additional scenarios, please list them out so that we could review and hopefully include them as it will greatly benefit the developer community.
3.    Yes, we do have code reviews. During the PR, it clearly states that “At least 1 approving review is required to merge this pull request.” Also, we have designated engineers performing this review, therefore we have not released guidelines on it as the reviewers are well aware of our guidelines and standards. Should your review not be approved, the reviewer would definitely leave a comment that includes improvements.
4.  Great suggestion. We are currently in the process of exploring such code coverage tools. If you have a recommendation along with reasons for the recommendation, please share the same with us.
5.  Once again, this is something we are currently in the process of exploring. Your expertise will be much appreciated. 
6.    We use Cpplint currently. No, we do not currently use Static code Analyzers. 
7.    We have increased the number of how-tos to support our developer community. If you have additional specific suggestions on documentation, please include them. We will be happy to increase our documentation to help the community.
8.   You are correct. 

Hope above information answered some of your questions. Please feel free to leave comments below if you have any additional questions. Again, we apologize for taking so long to get back to you, and thank you for your support in the Apollo Project.
