### ISSUE TITLE
Need for map docker images?

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#4046]
Why is there a separate docker image/container for each map ? Is there a specific reason for having maps in separate dockers ?

**Comment by xiaoxq** [comment]
Because HDMap is too big and updated often, comparing to other software dependencies. Docker image is a stack of layers such as [1...k...N], and you have to download [k...N] when layer k is updated on a single bit.
We don't want to bother users so much, so those *dynamic* and *huge* parts are pulled out as docker volumes, so as to update efficiently.
