### ISSUE TITLE
doesn't open Dreamview

### ISSUE THREAD

**Issue by lblblong** [ApolloAuto/apollo#4135]
From build to bootstrap.sh, everything works, but doesn't open Dreamview

**Comment by hushuitian** [comment]
I saw the same issue.

**Comment by siyangy** [comment]
Can you be more specific about how Dreamview is not working? Also taking a look at logs under data/log/dreamview* will also help reveal things that went wrong.

**Comment by hushuitian** [comment]
Hi,syangy, 
I just followed the README in https://github.com/ApolloAuto/apollo/tree/master to try to build and run the dreamview.
The dev PC is a Lenovo ThinkPad without nVidia GPU. The Ubuntu version is 16.04 installed the docker-ce per docker.io suggested linux installation steps and also added the user in order to use docker without sudo.   The docker version is 17.09.1-ce and go version is 1.8.3 and gcc version is 5.4.0.
The build and run steps are:
(1)git clone https://github.com/ApolloAuto/apollo.git
(2)cd apollo
(3)bash docker/scripts/dev_start.sh
(4)bash docker/scripts/dev_into.sh
#in dev docker
(5)./apollo.sh clean
(6)bash apollo.sh build
(7)bash scripts/bootstrap.sh
Every step seems OK except no ESD and no GPU warnings.
The issue is that http://localhost:8888 cann't be reached or accessed from Chrome browser after Step(7).
By the way,I have tried ./apollo.sh build_fe before or after step (6)bash apollo.sh build,I got the error message as:
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
yarn build v0.27.5
warning package.json: License should be a valid SPDX license expression
$ ./setup.sh; node_modules/.bin/webpack -p --progress
./gen_pbjs.sh: line 32: node_modules/protobufjs/bin/pbjs: No such file or directory
./gen_pbjs.sh: line 38: node_modules/protobufjs/bin/pbjs: No such file or directory
sh: 1: node_modules/.bin/webpack: not found
error Command failed with exit code 127.

I also tried "npm install pbjs" to try to fix the error.It didn't work. 
I checked data/log/dreamview.out per your suggestion.There is nothing in the dreamview.out file. 
So the dreamview doesn't work. 
Pls help to figure it out.
Thanks a lot for your help in advance!
-Alex

**Comment by lblblong** [comment]
@hushuitian @siyangy  
Thank you, it has been resolved.
Found a solution under other issues
Is a question about PCL Lib
I can already see Dreamview after recompiling PCL Lib
[#3615](https://github.com/ApolloAuto/apollo/issues/3615)

**Comment by siyangy** [comment]
@hushuitian You can run ./scripts/dreamview.sh start_fe to see how it exits abnormally, and if it crashed there would be a core dump file generated under /apollo/data/core, and you can use gdb to look into it. 

Also the frontend code is precompiled so you don't need to do ./apollo.sh build_fe.
