### ISSUE TITLE
tool not found: rosbag play -l ./docs/demo_guide/demo_1.5.np.bag

### ISSUE THREAD

**Issue by JerryOpenix** [ApolloAuto/apollo#4468]
Follow the guide: https://github.com/ApolloAuto/ApolloAuto.github.io, there's no "rosbag" command anymore when entering into the docker environment? Any change or previous build to generate rosbag tool?

**Comment by Grayhu07** [comment]
Are you experiencing "rosbag command not found" ? I think maybe you can try "$source /apollo/bazel-apollo/external/ros/setup.bash" to set rosbag and then re-run the command again.

**Comment by linux-devil** [comment]
@JerryOpenix Make sure you are running rosbag when you are inside docker (dev or release)

**Comment by yosuah** [comment]
I had the same issue. I could run `rosbas` by running `source scripts/bootstrap.sh` (instead of/on top of `bash scripts/bootstrap.sh`, which is mentioned in the official docs)

**Comment by zhxt** [comment]
If you got this `rosbag command not found` error  when you're inside docker env,  you're probably using the user 'root' for running Apollo.  

For use root , you may need to do some additional work:
 `source /apollo/scripts/apollo_base.sh` (this script include the ros environment setup procedure `source /home/tmp/ros/setup.bash`(for dev docker), or you can only source the ros env setup script as well).

Usually, this could be avoid by running Apollo as a normal user, since it will be configured into .bashrc automatically.

**Comment by yosuah** [comment]
Thanks @zhxt for the info, I did indeed use the `root` user (because the startup script threw an error for my regular user, as the user name contains a dot). Good to know I need to run these additional steps. Could you please add it to the docs so others can find it as well?

**Comment by zhxt** [comment]
@yosuah From the coming 3.0 release  which will release in early July(4th, July),  it will be forbidden to use user 'root' to run Apollo, there will be a error prompt if you're trying to user 'root'.  So temporarily I put this in the [wiki](https://github.com/zhxt/apollo/wiki/FAQ) of my fork.

**Comment by mickeyouyou** [comment]
if you have additional question, feel free and reopen or create a new issue. 
thank you so much.
