### ISSUE TITLE
Can I build Apollo in Ubuntu 18?

### ISSUE THREAD

**Issue by Yangshell** [ApolloAuto/apollo#4636]
As title. Can I build Apollo in Ubuntu 18?

**Comment by xiaoxq** [comment]
Yes and no.

Just follow the document to install docker, then `apollo.sh build` and `apollo.sh lint` should work. But `apollo.sh test` might not, because the nvidia-drivers are generally miss-matched between HOST and Docker container, which will rais several test failures.

**Comment by natashadsouza** [comment]
@Yangshell  did you face any issues in your installation? It would be great if you could share your experience building Apollo on Ubuntu 18. Thanks!

**Comment by SohamGhormade** [comment]
@hahanigehaha233 and @natashadsouza 
FYI I was able to follow @xiaoxq 's advice and build apollo as well as run the lint check with Ubuntu 18.I simply followed the instructions from [here](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md) .

Note that I followed the instructions to build without hardware because I do not have an actual car model with hardware on which I can use Apollo.

Running unit tests,I have hit a failing error due to NVIDIA graphics card issue earlier probably because I did not have drivers installed.
I have installed drivers recently so will let you know how that goes.

**Comment by SohamGhormade** [comment]
nvm...I am seeing a build failure with Ubuntu 19.04 today.
Here are the details about my Ubuntu version from terminal window:
![ubuntu_version](https://user-images.githubusercontent.com/9662026/45461847-292d7600-b6d3-11e8-8015-d4d2f8449e5a.png)
And here is the build output:

![build_failure 2018-09-12 21-29-09](https://user-images.githubusercontent.com/9662026/45461859-3ba7af80-b6d3-11e8-906b-7f96444c86dd.png)

Note that I built on the master branch after syncing with the ApolloAuto master and pushing to my forked repository's remote master.

**Comment by SohamGhormade** [comment]
Update: apollo.sh clean and then a build fixes the issue.
i.e I can build apollo code with Ubuntu 18.04.

**Comment by natashadsouza** [comment]
@SohamGhormade Thank you so much for the update. We are glad to hear that you were able to build Apollo on Ubuntu 18.04. As we mentioned before, Apollo has not been completely tested on Ubuntu 18 and hence you testing it for us is much appreciated!

**Comment by frontw** [comment]
> Update: apollo.sh clean and then a build fixes the issue.
> i.e I can build apollo code with Ubuntu 18.04.

Does perception module works for you in Ubuntu 18.04?

**Comment by ghormadesoham** [comment]
@frontw 
I can see that the build is passing(https://travis-ci.com/ApolloAuto/apollo) officially for officially supported Ubuntu versions.
I was able to *build* Apollo with Ubuntu 18.04 when I tried in September.
I however did not have the required GPUs to run the perception module.

So for your issue ,you can perhaps check existing issues or file a new one to ask this question.
Thanks and good luck
