### ISSUE TITLE
dreamview node keep alive problem

### ISSUE THREAD

**Issue by ImCabbage** [ApolloAuto/apollo#4676]
Recently I met a problem in starting dreamview with the latest code and newest image. I use the command
bash scripts/dreamview.sh start_fe 
But I got the error msg saying that another node with the same name exist. I could not even rosnode kill it.
I have checked my supervisorctl and confirmed that all the nodes are stopped and I could not see anything when I try to ps aux | grep dreamview. 
But it indeed exists in the rosnode list and could not be killed. 
I don't know why since some of my friends have encountered this.

**Comment by osaman88** [comment]
If rosnode list shows you a dreamview, then there is one that is alive but perhaps not on the local machine? Are there are machines in the system with same ROS_DOMAIN_ID that you might be pointing to? 
You can try the following commands to help you:
rosnode ping /dreamview
   -> Tells you if node is alive and responds to ping
rosnode info /dreamview
   -> Tell you some useful informaton about the node, including its process id (but again, note it may be on a different machine)

It is possible it cannot be killed because the unix process is owned by someone else and you don't have permission to terminate it.

**Comment by ImCabbage** [comment]
Hi,
I am pretty sure that the dreamview is not in the system process. So I got
nothing when I tried to rosnode ping this node.
Below is the screen shot of what I got when I run rosnode info /dreamview:

**Comment by siyangy** [comment]
Seems like a ROS problem, reassigning to @quning78

**Comment by ImCabbage** [comment]
Hi, Kevie,
Thanks for your information. Just want to kindly provide you with some
information based on my experience.

I use 16.04 outside the docker and I found most of my friends who met this
problem use it too. Those who use 14.04 do not have the same problem. I
guess one problem could be the compatibility problem with the system.

Another possibility could be the compatibility between two ROS which is
outside the docker and the one that you customized since my friends who
have not install ROS outside the docker did not have this problem.

BR,
Cabbage

**Comment by fengqikai1414** [comment]
Hi, @ImCabbage ,
We haven't tested enough on apollo docker on ubuntu 16.04 yet, and you should try to use the software configuration recommended by apollo. Of course, we will consider whether it is necessary to adapt ubuntu 16 later.
However, I have found some information here, which may help to solve this problem. [rosmaster leaves sockets in CLOSE_WAIT state](https://github.com/ros/ros_comm/issues/610)

**Comment by natashadsouza** [comment]
@ImCabbage have you resolved the issue you were facing?

**Comment by ImCabbage** [comment]
I changed back to Ubuntu 14.04 and have not met the same issue yet.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved in Ubuntu 14.04
