### ISSUE TITLE
实车上运行 third_party_perception 输出 perception obs 帧不完整

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#4690]
感知模块用了third_party_perception， 在实际输出的时候 输出的帧不完在 在有障碍物和道路线的时候周期性出现lanemarkers或者perception obs部分丢失的问题。
![webwxgetmsgimg](https://user-images.githubusercontent.com/16748704/41896057-35ec1438-7956-11e8-9ba7-a3d5fd06c317.jpeg)

从图片可以看出 这一阵缺失了道路信息 上一帧缺失了 障碍物信息 以道路信息结尾。导致planning模块障碍物出现闪动 影响路径规划。

**Comment by Capri2014** [comment]
@JonathanJones92  Third_Party_Perceptioin has not been actively maintained since the official release of Apollo 2.5. We recommend using perception module instead. -- But, could you elaborate more on the drivers you use and test environment? As far as we know, we did not open sourced the Mobileye drivers used by third_party_perception. -- Mind if I ask which drivers you are using?

**Comment by JonathanJones92** [comment]
@Capri2014  你好，谢谢你对这个问题的关心。 我们用了conti radar 和mobi EQ2，驱动自己开发。通过读取rostopic，驱动都能够输出完整的帧，就是感知出来的perception obstacles帧不完整，体现在前端就是感知到的障碍物存在周期性闪动。 目前来说解决的方法是降低感知刷新频率，由20降低到10一下，可以缓解闪动。但是不知道为什么会出现这种现象，三方感知的所有主函数都加了进程锁，应该不存在信息没有准备好就提前通过timer触发 publish而导致帧数据缺失啊。 后面我会提供更详细的数据作为支持。

**Comment by Capri2014** [comment]
@JonathanJones92 Check過你們driver的輸出過麼？....Mobileye本身的輸出頻率都不到20HZ吧....

**Comment by JonathanJones92** [comment]
@Capri2014  mobi 的频率是40HZ，通过EQ2的data sheet可以得到，而且读 mobi的 rostopic可以看出timestamp里确实是更新频率是40HZ。 如下是两帧数据：
 timestamp_sec: 1530062266.99
  module_name: "mobileye"
  sequence_num: 9474



  timestamp_sec: 1530062267.07
  module_name: "mobileye"
  sequence_num: 9475

**Comment by JonathanJones92** [comment]
目前通过修改测试频率，可以得到，感知模块在8HZ的更新频率障碍物闪动较少，可以接受。

**Comment by JonathanJones92** [comment]
此问题可以关闭。
