### ISSUE TITLE
brake60::ID. what does this ID mean?

### ISSUE THREAD

**Issue by apycii** [ApolloAuto/apollo#4774]
Hello Apollo team,

Brake60::ID sets 0x60 in apollo/modules/canbus/vehicle/lincoln/protocol/brake_60.cc. Does this ID mean a CAN Bus Identifier?

If the answer is yes then, why send protocol ID is different from receive protocol ID even if they are same module.

ex)
send protocol brake60 ID is 0x60
receive protocol brake61 ID is 0x61
they both are brake but ID is different.

**Comment by follow123** [comment]
In apllo,  CANbus just a moudle, like control, planning,and so on. Others moudle, like control or localization moudle, send message to canbus moudle, then canbus deal them and send them to the CANBUS(the true CANbus) by period.

Receive messages: from Apollo_moudle to CAN_CLIENT_, have 5 messages:
break_60
throttle_62
steering_64
gear_66
turnsignal_68

Send messages: from CAN_CLIENT_ to CANBUS, have 18 messages:

brake_61
throttle_63
steering_65
gear_67
misc_69
wheelspeed_6a
accel_6b
gyro_6c
gps_6d
gps_6e
gps_6f
tirepressure_71
fuellevel_72
surround_73
brakeinfo_74
throttleinfo_75
version_7f
license_7e

They all have their own correspondence ID, because the information they carry is different. For details, please carefully parse the `.cc` and `.h` files corresponding to each message and canbus.cc, and combining the corresponding module of the message to analyze, it may be more convenient to understand.

One more thing, the message format of CANBUS is in the DBC format.

Hope that can help you.

**Comment by natashadsouza** [comment]
Closing this issue as it is resolved. @follow123 thank you for providing such a detailed response.
