### ISSUE TITLE
Question about the role of Ultrasonic Sensor in Apollo 3.0

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#4910]
Hi Apolloteam, Apollo 3.0 was released last week and you are doing a lot of hard work.

I read some documents about Apollo 3.0 and I have question about Ultrasonic sensor.

The `Guardian` Module is newly launched and it seems to take some actions(soft stop or hard braking for the gatekeeping function) based on ultrasonic sensors.
And ultrasonic sensors are built-in MKZ vehicle, right?

What I know about general ultrasonic sensor, it's valid detecting range is not that long. Then, how can ego-vehicle make a decision to execute AEB(Autonomous Emergency Brake) based ultrasonic sensor data?

I want to know how Guardian module works with ultrasonic sensors. Thanks !

**Comment by natashadsouza** [comment]
@CCodie Guardian module takes its decision based on the signals produced by Monitor and not solely based on the Ultrasonic sensor. There are 2 scenarios:
1. If all modules are working fine, then Guardian does nothing.
2. Monitor detects a failure in a module or a hardware device, and sends a signal to Guardian. In order to understand if that fault will cause an immediate crash, the output from the Ultrasonic sensor is verified, should the sensor not detect an immediate crash, the car is brought to a slow stop. If the sensor detects an obstacle or if the sensor does not respond at all, a hard brake is applied. 

You were right about the detection range being limited and hence, the decision is not based of the sensor's output alone. Hope this answers your question. Let me know if you have any additional questions. Thanks!

**Comment by jinghaomiao** [comment]
@CCodie if an ultrasonic sensor detects an obstacle, it means it's fairly close to the vehicle. Thus it's likely Guardian kicks in to issue soft/hard stop command.

**Comment by Zhenni17** [comment]
Closing the issue due to no further communication. Feel free to re-open it if there are follow up questions.
