### ISSUE TITLE
Question about planning and control.

### ISSUE THREAD

**Issue by YaoQii** [ApolloAuto/apollo#4992]
Hello,
I have a question about trajectory points in planning and control.
1. In planning, the points in trajectory is the center of rear axle of vehicle.
2. In control, the points used in MPC controller is the centroid of vehicle.

Can they work well to follow the path? 

Thanks.

**Comment by berthu** [comment]
When a vehicle deviates from the planned trajectory, usually a heading error (rather than a lateral error) appears first, causing a forward-moving vehicle to veer off a predicted course, which translates to a lateral error. In other words, lateral errors are lagged with respect to heading errors. By moving the controller origin forward, lateral errors appear sooner upon vehicle deviation, which improves controller stability.

Planning, in theory, does not need to know where a controller thinks the vehicle origin is. All it cares is that the vehicle is able to stay on a planned trajectory with small predictable deviations.
