### ISSUE TITLE
Multiple time sources in Apollo

### ISSUE THREAD

**Issue by rogern27** [ApolloAuto/apollo#5029]
Hi,
In Apollo 2.5, the /tf (or sensor Velodyne) gets the time from GPS and radar and camera gets their time from ROS. It can be noted that  the GPS time and ROS time can be off by few seconds. In the perception module, it gives issues in transformation. 
E.g., get the interpolated pose information corresponds to the radar/camera data.

Have anyone of you had the issue? or is there any solution planned for this?

**Comment by hzdsdhr** [comment]
That's big issue for perception. I also try to figure out why multiple time sources instead of using ROS time only. To fix the time difference, you need to make your system time(ros time source) to be close to the gps time. In fact, apollo provided the script for synchronizing your system time to real time under scripts/time_sync.sh. Try to use it in host before enable perception module.

**Comment by natashadsouza** [comment]
@rogern27 you could resolve this issue using the [Time sync script](https://github.com/ApolloAuto/apollo/blob/master/scripts/time_sync.sh) as @hzdsdhr mentioned. Please let us know if you have any additional questions.
