### ISSUE TITLE
bash apollo.sh build failed

### ISSUE THREAD

**Issue by fenglupeter** [ApolloAuto/apollo#5166]
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1470 targets (12 packages loaded).
INFO: Found 1470 targets...
ERROR: /home/autolab/.cache/bazel/_bazel_autolab/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:113:1: C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Exit 1)
In file included from external/com_google_protobuf/src/google/protobuf/generated_message_table_driven.cc:1:0:

/usr/include/x86_64-linux-gnu/asm/param.h:1: confused by earlier errors, bailing out
INFO: Elapsed time: 514.355s, Critical Path: 510.16s
FAILED: Build did NOT complete successfully
============================
[ERROR] Build failed!
[INFO] Took 808 seconds
============================

**Comment by draturi** [comment]
We have experienced the same problem, it seems the latest docker image does not come pre-loaded with the bazel/protobuf dependencies under the '/home/tmp/' directory. This leads to bazel runtime not being able to find the packages and therefore failing.

**Comment by DongAi** [comment]
Hi, fenglupeter. protobuf must be built with a particular bazel version, because some features in protobuf are not compatible with some bazel version.
So, please  tell me your docker_dev version, use instruction `'docker images' `to show all images; your  bazel version, in docker_dev, use instruction `'bazel --version'` to show bazel info; your protobuf version, in docker_dev, protobuf file is in directory `/home/tmp`.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if the issue persists. Thanks!

**Comment by arappazzo** [comment]
Please re-open the issue. I suspect issue #10159 is actually another version of this one.
Bazel version: 0.5.3
