### ISSUE TITLE
No module named google

### ISSUE THREAD

**Issue by SanduIrina** [ApolloAuto/apollo#5228]
Hello guys, I'm trying to run some python scripts outside of the docker_dev image and I get the error No module named google. In the script I'm using some protobuf files like map_road_pb2. Is there anything else I should add to the python path? In the docker image importing map elements works perfectly fine, but I can't keep working there because I need python3 and the docker image has python2.7.

**Comment by DongAi** [comment]
HI, Sandulrina, do you mean

>  'no module named google.protobuf'

If it's that case, it shows that you havn't installed protobuf in you operation environment out of docker_dev. You operation environment and `docker_dev` where apollo works in are two different environments, we could even recognize them as two different OS.

Apollo developers have installed protobuf in `docker_dev`, so it works well, but if you want to do the same work out of `docker_dev`, there are some installations you must do. 

You can use `'pip install protubuf' `to install protobuf package for python, but with resolving this error, there may be more errors waiting you since the environments are diffenent completely. Be Careful!

**Comment by SanduIrina** [comment]
Thank you very much for your answer. I already had protobuf installed with pip for both python2.7 and python3.6 but after running pip install protobuf and pip3 install protofbuf once more it worked!! Not sure what the problem was.

**Comment by Zhenni17** [comment]
Closing the issue as it seems to be fixed.
