### ISSUE TITLE
Which coordinate system is correct and which should I use?

### ISSUE THREAD

**Issue by xinwf** [ApolloAuto/apollo#5238]
There is a difference explanation about coordinate system in [docs/specs/Guideline_sensor_Installation_apollo_2.5.md](https://github.com/ApolloAuto/apollo/blob/r2.5.0/docs/specs/Guideline_sensor_Installation_apollo_2.5.md) and [docs/specs/coordination.pdf](https://github.com/ApolloAuto/apollo/blob/r2.5.0/docs/specs/coordination.pdf)

**Comment by DongAi** [comment]
Hi, xinwf, do you mean the pictures in docs/specs/Guideline_sensor_Installation_apollo_2.5.md? There may be something wrong with the orientation shown in those pictures. The coordinate system shown in docs/specs/coordination.pdf is correct since the vehicle coorinate system is based on Right-Forward-UP(RFU). And the origin is at the center of the rear wheel Axle. If have other confusions, please contact me.

**Comment by xinwf** [comment]
Ok, thank you very much!
