### ISSUE TITLE
[request]Switching the state of traffic lights in dreamview

### ISSUE THREAD

**Issue by poutyface** [ApolloAuto/apollo#5593]
In SimControl mode, I want the function of switching the state of traffic lights in dreamview.
 I would like to do the function of tools / manual_traffic_light in dreamview, however I am not familiar with react program.😥

thanks

**Comment by unacao** [comment]
There are two parts to this feature. First part is the addition of a frontend UI switch to toggle traffic lights as you mentioned. However we need to integrate with the backend messages so that the entire system gets the updated traffic light status and modules such as planning can react accordingly, which means we need to make sure: 1. there are no other traffic light status being published by the perception modules so that there is no data corruption, 2. the frontend traffic light status needs to be communicated with the backend.
We can definitely add this feature in our future task list.

**Comment by poutyface** [comment]
@unacao , @lianglia-apollo  Thank you for  your reply. Usually I use manual_traffic_light.

It is useful to set directly some configuration from HMI.  For example, a speed limit, a distance from CIPV etc.. 

Anyway, I need to learn about React. Thanks.
