### ISSUE TITLE
I want to port apollo3.0 and apollo-ros-indigo to QNX OS + NVIDIA PX2 platform

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#5618]
**Is your feature request related to a problem? Please describe.**
I want port apollo3.0 and apollo-ros-indigo to QNX OS

**Describe the solution you'd like**
first I want to port apollo-ros-indigo to qnx os system 
then the apollo3.0 to qnx 

so I want some advice about port apollo-ros-indigo and apollo3.0 to qnx 

now I have port boost and protobuf and leveldb and glog gtest to qnx + nvidia px2 .

but for the apollo-ros-indigo I do not know how to start it . because indigo is not compile by cmake or configure. can anyone give me some advice?

**Comment by zhxt** [comment]
What do you mean "not compile by cmake" ?
To my knowledge, ROS is composed of many separated packages which use cmake as build system.(catkin_make/catkin_make_isolated is a wrapper Python script  tool that use cmake +  make + package.xml).

So I think, these steps bellow,
1. prepare the dependencies;
2. then build the sources with catkin_make_isolated(or just use the [build.sh script](https://github.com/ApolloAuto/apollo-platform/blob/master/ros/build.sh#L74));
3. fix the build error and repeat until all packages passed.

would be one way,
or, instead of using catkin tool , you can also manually build the packages with cmake & make in topological order one by one.(not prefer)

Moreover, AFAIK, the QNX team made some progress on porting Apollo to QNX.

![migrating apollo to embedded world](https://user-images.githubusercontent.com/552937/44993837-9142d480-afce-11e8-9d2e-c550be3c6b57.jpg)
![apollo on QNX](https://user-images.githubusercontent.com/552937/44993847-9b64d300-afce-11e8-8a97-4569bc2bd76e.jpg)

**Comment by jilinzhou** [comment]
To x-compile ROS onto qnx is not a trivial task. A lot of third party dependancies need to be figured out first. Here is a brief list (There might be more):

- lz4
- boost
- tinyxml
- mktemp
- eigen3
- gtest
- gflags
- glog
- protobuf
- pcl
- poco
- yaml
- fast-rtps
- console_bridge
- curlpp
- fastcdr
- gtsam
- GeographicLib
- qhull
- proj
- qpOASES
- yaml-cpp
- uuid

Some code changes are also needed for some third party dependancies and ROS packages.

**Comment by jilinzhou** [comment]
@zhxt : Posting some slides which clearly state " Confidential" may not a good idea.

**Comment by Capri2014** [comment]
Close it since improper material posted.

**Comment by zhxt** [comment]
@jilinzhou @Capri2014  Sorry about that, I didn't notice that label.
I got the pictures from an **Open Course Lecture** at Create2018 BAIDU AI Conference.  I was thinking it would be OPEN.
