### ISSUE TITLE
Help wanted regarding to the Route Editing function in DreamView

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#5727]
Dear Apollo Developers: 

I have a question regarding to the usage of the Route Editing function under DreamView category. 

- could you tell me how to set up the starting and end point of a route without affecting other default routes? Currently, if I put several points of interests on the map, the routing module would create a route which starts from a point that is on the last default route I chose and then connect all the way to the closet point of interests. I'm wondering what is the logic behind it? 

- Sometimes when the vehicle reaches a junction, the vehicle stops because of the existence of a stop sign or traffic light. Then the vehicle just stuck there and never move again although the route has not been completed yet. Could you also help he solve the problem?

### System information

- **OS Platform and Distribution Ubuntu 14.04**:
- **Apollo installed from source **:
- **Apollo version 3.0**:

**Comment by vlin17** [comment]
For routing editing behavior, it depends on how many POIs are set when sending the routing request:
- Minimum required POI is 1
- If only one POI is set, then start point is current ego-vehicle position, and end point is the given POI.
- Otherwise, the start point is the first given POIs, and end point is the last given POIs

The second part of the questions is related to planning module.  Assigning to planning related developer for a further look. @lianglia-apollo

**Comment by yangydavid** [comment]
Thanks @vlin17 , your input is very helpful :)

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
