### ISSUE TITLE
How to calculate stbounday() ?

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5751]
Hi Guys,

I have been going through the Apollo code and having difficulty in understanding how the stboundary() is calculated. I got the point that stboundary it is the "s" values with respect time. However I got the below doubts when going through the st_boundary.cc program. 

1. t value - does this start when the routing starts ?

2. s values - Could you please let me know from which point the values are being calculated / measured ? Is it taken with respect to Reference line starting ?

3. If stboundary is empty (IsEmpty() is true), does that mean the obstacle is not moving ?

4. What does the below functions return in stboundary class
```
        double min_s() const;
        double min_t() const;
        double max_s() const;
        double max_t() const;
```

5. Do we see Stgraph on PNC monitor ? 
    Is QpSplineStSpeedOptimizer is same as ST graph ? 

6. Also similar condition is being checked in backside_vehicle.cc. Could you please explain the below piece of code. 
```
    // Ignore the car comes from back of ADC
    if (path_obstacle->reference_line_st_boundary().min_s() < -adc_length_s) {
      path_decision->AddLongitudinalDecision("backside_vehicle/st-min-s < adc",
                                             path_obstacle->Id(), ignore);
      path_decision->AddLateralDecision("backside_vehicle/st-min-s < adc",
                                        path_obstacle->Id(), ignore);
      continue;
```

Thank you,
KK

**Comment by jmtao** [comment]
@kk2491 
(1) t value is for time. we plan 0-6s
(2) s: start with the current position of the ego vehicle
(3) it means the obstacle's path would not cross with ego vehicle. 
(4) these returns the st boundary of an obstacle.  min_t() and min_s() are the (x,y) of the left lower point, max_t() and max_s() are the (x,y) of the right upper point. 
(5) yes. StZGraph is on PNC monitor. 
(6) looks like we shall use max_s() in order to check if another obstacle behind ego vehicle and shall be ignored.  We'll revisit the code.

**Comment by jmtao** [comment]
Hi @kk2491 hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
