### ISSUE TITLE
apollo 3.0 navigation mode question

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5779]
Dear apollo developer,
- Apollo version 
3.0

apollo 3.0 navigation mode support Multi Lane？

![image](https://user-images.githubusercontent.com/19250516/45794316-9b501d00-bcc8-11e8-9837-440a7968497e.png)

in the picture, can our vehicle run from left lane to middle lane when in the front of the car have obstacle ?
I read  this infromation:
https://www.csdn.net/article/a/2018-04-24/15946728

It description as follow:
         ===>目前，导航模式仅支持单车道行驶，可完成加减速、跟车、遇障碍物减速停车或在车道宽度允许的情形下对障碍物绕行等功能，后续版本的导航模式将会进一步完善以支持多车道行驶、交通标志和红绿灯检测等。

for apollo 3.0 ,have further development in navigation mode?

**Comment by jilinzhou** [comment]
The information you read was from 2018-04-24. Outdated!

**Comment by freeclouds** [comment]
@jilinzhou so, the latest about navigation can mode support Multi Lane?

**Comment by verasnt** [comment]
Anyone trying to solve this? if no, i'll give it a try!

**Comment by yifeijiang** [comment]
Navigation mode supports multiple lanes and lane change in Apollo 3.0. You could use following command to send out multiple navigation lines: 

dev_docker:/apollo/modules/tools/navigator$python navigator.py navigation_line_1 navigation_line_2

in this example, navigation_line_1 navigation_line_2 could be navigation line on two adjacent lanes. And navigation_line_1 has higher priority than 2.

**Comment by daviduhm** [comment]
If Navigation mode supports multiple lanes and lane change, how does it detect other cars and avoid collisions when lane changing? What happens if there is a car coming from behind when the ego vehicle tries to change lane?

As far as I understand, Apollo 3.0 navigation mode uses front-facing camera and frontal radar only which means there is no LiDAR or other sensors to detect obstacles behind or beside.

Any clarification would be appreciated!

**Comment by yifeijiang** [comment]
@daviduhm If no sensors are supported for detecting back and side obstacles, you can use a manual input to trigger lane change
