### ISSUE TITLE
How to debug in dreamland

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#5853]
Hi,

I am using dreamland to verify my motion planning algorithm. My algorithm works well in dream view simulation, but it could not run in dreamland. The result is failed because of "error".
How do I detect what is the error here? it does not give any more information other than that.

thank you

**Comment by lesun90** [comment]
hi,

I could not find where to download error log. I only see the debug/play button.
And how to get the task id? 

Thank you.

**Comment by siyangy** [comment]
The task id is in the URL of the page you see the debug/play.

**Comment by lesun90** [comment]
Here the task id:
597aeb58b11096000a888220

Thank you for your help

**Comment by siyangy** [comment]
That doesn't seem to be a valid task id, what you see in the URL should be something like https://azure.apollo.auto/multidetail?id=<task-id>&locale=en-us

**Comment by lesun90** [comment]
I think this is the correct one.
5bbe297eca04120016dd6ed0

Thank you for your support.

**Comment by siyangy** [comment]
It looks like your planning algorithm was stuck in some infinite loop and was thus killed by the system due to timeout. 

The log I'm seeing is: 
`
E1010 16:37:14.642369   159 file.h:97] Failed to open file /apollo/modules/map/data/map//speed_control.pb.txt in text mode.
E1010 16:37:14.642563   159 file.h:140] Failed to open file /apollo/modules/map/data/map//speed_control.pb.txt in binary mode.
W1010 16:37:14.644086   159 em_planner.cc:266] last frame is empty
I1010 16:37:14.644259   159 rrts_road_graph.cc:32] has_stop_point
I1010 16:37:14.644340   159 rrts_road_graph.cc:306] plan_history_.size() :0
`
FYI we are considering opening debug capability in the near future so that you can have access to the log.

**Comment by lesun90** [comment]
thank you,

I was using a clock timer as the terminate condition for a while loop, that might the reason it stuck in an infinite loop. After I change the terminate condition (not using a clock timer), there is no problem.
My code (with clock timer) works fine in my machine, so the clock function might not work properly in the server. Can you guys please check that?

Thank you for your support.

**Comment by siyangy** [comment]
We may have to know how the clock timer is implemented in order to know why it doesn't work in the server.

**Comment by lesun90** [comment]
oh, it is really simple, I want the code to "do something in 50ms"
double start_time_ = Clock::NowInSeconds();
while (Clock::NowInSeconds() - start_time_ < 0.05) {
    $do something
  }

**Comment by siyangy** [comment]
I see, so this is expected as in simulation the Clock mode is set as MOCK so that NowInSeconds will always return the same time. I recommend calling system library to get real time, something like:
```
double RealTimeNow() {
  auto now = std::chrono::system_clock::now().time_since_epoch();
  return std::chrono::duration_cast<std::chrono::seconds>(now).count();
}
````

**Comment by lesun90** [comment]
got it, thank you for your support.
