### ISSUE TITLE
Navigation Mode Question 

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#5884]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (master)**:
- **Apollo version (3.0)**:

### Steps to reproduce the issue:
- I was following the navigation mode manual at the following place:[http://articles.csdn.net/plus/view.php?aid=15946701](url), which was the same article posted on Apollo's github page. when I play the recorded bag under the navigation mode, there no blue planning trace shown in front of the car. Also, I was not able to turn on the "Navi Planning" button in the module controller tag. I am wondering what is the main issue causing this happening. 

- I've actually also change the file "planning_config_navi.pb.txt" as well as "planning_config.pb.txt", both planner_type were set as "NAVI",  but nothing changes before or after I did the modification. 

I am hoping if anyone of you could help me out here figuring out why I cannot turn on the Navi Planning module, it seems very weird to me. 

Best,
Thank you all.

**Comment by daviduhm** [comment]
Seems like you're having the same issue as mine. You can check log messages from ``/apollo/data/log/planning.INFO`` or by running ``bash scripts/navigation_planning.sh start_fe`` from command line. If it's crashing because of some thread related issues, then I've fixed this issue and you can check PR here: https://github.com/ApolloAuto/apollo/pull/5885

**Comment by yangydavid** [comment]
@daviduhm  Hi dude, I could not even find my `planning.INFO` file under the `/apollo/data/log` folder. It looks like it was never generated. 

I tried the `start_fe` command and nothing changes either. could you tell me how to fix this issue in a detailed way? I really appreciate it. 

Btw, unlike what described in the article, after I send the smoothed reference line, the lane boundary would be covered by a red curve, underneath of which was the original white lane boundary.  Do you by any chance know what causes it ? 

Best, 
Thank you!

**Comment by daviduhm** [comment]
I'm sorry but without seeing any log messages, it's hard to tell what's causing your issue. If you can't even launch the navigation planning module either from dreamview or command line without any error messages, my guess is that you did not build Apollo correctly. Otherwise, you should be able to see some log messages when you run it with ``start_fe``. You can check my fix more in detail from this PR: https://github.com/ApolloAuto/apollo/pull/5885 (see which files I've changed there).

For the red curve, I'm not sure about what article you're referring to (the link above is not correct), but as far as I know that's normal behavior when you send the navigation line data via ``python navigator.py some-path-file.bag.txt.smoothed``.

**Comment by jmtao** [comment]
Hi @yangydavid,  we haven't heard from you for a while. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
