### ISSUE TITLE
What are concept of 'overtake_obstacle' & 'guard_obstacle' in ChangeLane rule of TrafficDecider

### ISSUE THREAD

**Issue by quhezheng** [ApolloAuto/apollo#5994]
I can't understand the concept of 'overtake_obstacle' & 'guard_obstacle' in ChangeLane rule of TrafficDecider. The logics don't match with their name very much, the codes are confusing.

 Appreciated if  given some pointers on these. 

### overtake_obstacle 

- From the logic,  I think the obstacle behind the ADC and beyond the threshold distance should be taken care of as 'overtake_obstacle'. Why need to take of those far behind ADC instead of the nearing obstacles?
- How would these 'overtake_obstacle' be taken care of in the  planing logic after?

### guard_obstacle
- From the logic, I think only the obstacles behind ADC and going to run into the front of ADC within a threshold distance should be taken care of as 'guard_obstacle'.  Can you describe a little bit of the scenario in term of the behaviour?  Why those end up beyond the threshold distance should not be taken care of?

**Comment by poutyface** [comment]
Me too.
Is there an illustration showing the behavior of planning?

**Comment by lianglia-apollo** [comment]
guard and overtake obstacle are vehicles in front of or at the back of the ego vehicle when making a lane change. Please refer to the change_lane.h for more details, e. g. "
   * @brief This function will extend the prediction of the guard obstacle to
   *guard lane change action. Due to the ST path may drive on the forward lane
   *first, then slowly move to the target lane when making lane change, we need
   *to make sure the vehicle is aware that it actually occupies the target lane,
   *even when it is not on the target lane yet."

**Comment by jmtao** [comment]
Hi @quhezheng @poutyface  , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Comment by UstcJason** [comment]
I met the same question，especially what  dose the overtake obstacle mean? Why far behind obstacles is considered?
