### ISSUE TITLE
modify routing result

### ISSUE THREAD

**Issue by wujiyoung** [ApolloAuto/apollo#5998]
Hi, I am trying to use custom message to test my planning algorithm, but I do not have any routing reference line. However, a routing result is necessary to planning module, so I wonder if there is any way I can modify routing result and send a custom reference line to planning module?

**Comment by lianglia-apollo** [comment]
In dreamview, there is a button to generate routing based on your map. When you receive that routing msg, you can try to modify it based on your needs.

**Comment by jmtao** [comment]
@wujiyoung in dreamviiew, 
(1) start docker and dreamview
(2) click "Module Controller" on left-side panel, and turn on "Routing" from Modules list
(3) play a bag file, so that a map can be loaded into dreamview UI
(4) click "Route Editing"  on left-side panel, and then pick start/end points by right clicking on the map, and then "Send Routing Request" from the menu on the top. 
Now a routing request would be send,  and Routing module would handle it and broadcast routing response.
