### ISSUE TITLE
Why transform only applicable when navigation mode is enable 

### ISSUE THREAD

**Issue by GPrathap** [ApolloAuto/apollo#6129]
**Describe the bug**
Let's say we have more than one camera where each camera has its own coordinate system. Thus, before applying to filter it should be transformed into a common coordinate frame (car). So I believe [transformer_->Transform(&objects);](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc#L172) should be applied even when navigation mode is disabled. 

Also, if this transform is enabled is camera_process_subnode.cc, transform in the [object_camera_filter.cc](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/camera/filter/object_camera_filter.cc) is not needed. 
[https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/camera/filter/object_camera_filter.cc#L111 ](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/camera/filter/object_camera_filter.cc#L111 ), [https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/camera/filter/object_camera_filter.cc#L196](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/camera/filter/object_camera_filter.cc#L196 )

Please correct me if my assumption is wrong. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04
 - Browser Chrome

**Comment by xmyqsh** [comment]
@GPrathap 
Your assumption seems wrong.
Although the code of this [camera_process_subnode.cc](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc) does not as clean as others, the logic has no problem.
When it is under the navigation mode, the objects transform from camera coordinate to car coordinate [transformer_->Transform(&objects);](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc#L172) before [filter_->Filter(timestamp, &objects, options);](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc#L196). 
While, when use_navigation_mode is false, the objects were filtered [filter_->Filter(timestamp, &objects, options);](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc#L196) directly. But the camera to world transformation is packeted into `option` [if (!GetCameraTrans(timestamp, options.camera_trans.get())) {](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc#L188), and then transformed in filter [filter_->Filter(timestamp, &objects, options);](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc#L196). 

Right, the navigation mode is on relative coordination(the car coordination). Otherwise, the world coordination.

**Comment by GPrathap** [comment]
@xmyqsh Did you see the difference between [transformer_->Transform(&objects);](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/camera/transformer/flat_camera_transformer.cc#L24) and transform which happens inside transformed in filter [void ObjectCameraFilter::TransformObject(std::shared_ptr<VisualObject> obj,
                                         const Eigen::Matrix4f& pose)](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/camera/filter/object_camera_filter.cc#L137). What I believe is that both cases it should be in the same way. 

And why do you think trasformation is happes two differnt places based on navigation mode?

**Comment by xmyqsh** [comment]
@GPrathap 
Haha, I have said this code part is not clean.
See here,
```
if (FLAGS_use_navigation_mode) {
    options.camera_trans = std::make_shared<Eigen::Matrix4d>();
    options.camera_trans->setIdentity();
  } else {
    options.camera_trans = std::make_shared<Eigen::Matrix4d>();
    if (!GetCameraTrans(timestamp, options.camera_trans.get())) {
      AERROR << "failed to get trans at timestamp: " << timestamp;
      return;
    }
  }
```

I think you have not noticed this line [options.camera_trans->setIdentity();](https://github.com/ApolloAuto/apollo/blob/v3.1_dev/modules/perception/obstacle/onboard/camera_process_subnode.cc#L185)

**Comment by GPrathap** [comment]
Yes, if you dont understand better not to comment :)

**Comment by xmyqsh** [comment]
@GPrathap 
Got it. You are right, guys!! Bugs here.
I haven't digged into object_camera_filter.cc before.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
