### ISSUE TITLE
Current Lane of the Ego vehicle

### ISSUE THREAD

**Issue by BoChang11** [ApolloAuto/apollo#6710]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Could you please let me know how we can fetch the current lane on which Ego vehicle is currently present. I am using the below code snippet, however it is returning more than 2 lanes. How can I get single lane information. 

```
  const int status = HDMapUtil::BaseMap().GetLanes(point, 0.005, &lanes);
  static double speed_limit = 0;
  int lane_counter = 0;
  for (auto& lane: lanes){
    const hdmap::Lane& single_lane = lane->lane();
    speed_limit = single_lane.speed_limit();
    lane_counter = lane_counter + 1;
    // ADEBUG << "Speed Limit : " << speed_limit;
  }
```

### Supporting materials (screenshots, command lines, code/script snippets):

BR

**Comment by jmtao** [comment]
@BoChang11 If you want to get the lane(s) by point, the map may return your multiple lanes since some lanes are overlapped (especially around junctions and turns). This is as expected. 
The lane by point is only unique if you talk about the lanes along  the routing. There are some methods inside ReferenceLine class to get it. 
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/reference_line/reference_line.h

Hope this answers your questions. 
Thanks for supporting Apollo!

**Comment by BoChang11** [comment]
@jmtao thanks for the details. As mentioned above I was able to get the current lane details. Yes, you are right, we would get more than one lane if there is overlap.
