### ISSUE TITLE
PathDecider tag: not-in-s, not-in-l, nearest-stop, not-nearest-stop. What do they mean?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#7053]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by jmtao** [comment]
@KevinYuk these tags are decision tags, used to indicate who/why these decisions are made, mostly for debugging purpose.  If you read code in PathDecider (https://github.com/ApolloAuto/apollo/blob/master/modules/planning/tasks/optimizers/path_decider/path_decider.cc), they are self-explanatory. 
* not-in-s: the obstacle's s is not in the s range along the path we are planning, either too far away or behind us.  the corresponding decision is IGNORE
* not-in-l: the obstacle's l is not in the l range along the path we are planning.  the corresponding decision is IGNORE
* nearest-stop: this STOP obstacle decision is closest (in terms of distance) to us, compared to the STOP decisions from other obstacles, and therefore its info will be used as the STOP decision for main decision (e.g., if there are multiple STOP decisions from multiple obstacles, main decision will use the one whose stop line is ahead of us and closest to us). 
* not-nearest-stop: otherwise

Hope this answered your question. 
Thanks for supporting Apollo!
