### ISSUE TITLE
bazel 0.5.3 how to use cross-toolchain, for example, yocto sdk (aarch64)

### ISSUE THREAD

**Issue by jaloo2018** [ApolloAuto/apollo#7184]
I'm porting the Cyber RT to NXP S32V234 platform, and need to cross compile the Cyber RT with bazel, but there isn't any documentations about setting CORSSTOOL of bazel 0.5.3, according the bazel 0.21.0 docs, got lots of problems. So can i get some help from ApolloAuto about the questions?
             1. how bazel 0.5.3 works well with cross-toolchian (for example, aarch64 SDK made from yocto) ?
             2. how to porting the Cyber RT to ARM platform ?
thanks.

**Comment by natashadsouza** [comment]
@jaloo2018 unfortunately you would have to look into the Bazel documentation. We do not have documentation that would help in this case.

**Comment by aboarya** [comment]
@jaloo2018 I've been working on this from time to time as well.  Remember to build Fast-RTPS first.  There's a trick there as well, since the latest CyberRT code uses Fast-RTPS that's not compatible with the pre-built binaries in the [apollo-platform](https://github.com/ApolloAuto/apollo-platform/tree/master/ros/third_party) repo.  Still work-in-progress for me.

**Comment by bssung** [comment]
@jian3os  Do you find a way to cross-compile in bazel 0.5.3 ?
