### ISSUE TITLE
关于把自己修改过的caffe和tensorflow集成 进Apollo的问题

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#7459]
现在我在 docker 内部有apollo3.5用 bazel 管理依赖和编译，里面有很多第三方依赖，比如 gflags、opencv、gtest、blas、caffe 等等

然后我们需要自己编译一个修改过版本的 caffe，之前是在在 docker 外部编译好 caffe，然后把对应的头文件和.so 拷入 docker 镜像内部，也能运行。但是今天发现不对，因为 caffe 也依赖了 blas 等库，在外面 build 的 caffe 依赖的 blas 等库的版本可能不一样，拷进去恰好能运行只是刚好依赖的版本接近，从原理上来说是有风险的。。。同样的 tensorflow 也有这个问题

解决方案无非 2 种：1，编译静态链接的 caffe 和 tf 2，第二就是把 caffe 和 tf 搬到 docker 内部的 bazel 工程里，统一用 bazel 编译

我这个分析对么？

**Comment by natashadsouza** [comment]
The translation to his question is:

Now I have apollo3.5 inside docker to manage dependencies and compiles with bazel, which has many third-party dependencies, such as gflags, opencv, gtest, blas, caffe, etc.

Then we need to compile a modified version of caffe ourselves, before compiling caffe outside of docker, and then copying the corresponding header file and .so into the docker image, it can also run. But today I found it wrong, because caffe also relies on blas and other libraries. The version of the blas and other libraries that are built on caffe may not be the same. Copying in just happens to be able to run just the version that just depends on, which is in principle risky. . . . The same tensorflow also has this problem

There are no more than two solutions: 1. Compile the statically linked caffe and tf 2, and the second is to move caffe and tf into the bazel project inside docker and compile with bazel.

Is this my analysis correct?

**Comment by gengqx** [comment]
you could build your caffe in the apollo docker,but no need to use bazel to build caffe,but just use those dependencies,then you can copy the caffe lib to another apollo docker container,use ldd to check the dependencies,then commit the docker.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you additional questions. Thanks!
