### ISSUE TITLE
planning architecture introduction issue?

### ISSUE THREAD

**Issue by daohu527** [ApolloAuto/apollo#7654]
This could be a documentation error. 
```
Version : apollo 3.5 (lastest master branch)
Url: https://github.com/ApolloAuto/apollo/blob/master/modules/planning/images/planning_architecture.png
```
I saw a document about planning readme.md. The introduction is very helpful. But I have some doubts about the "planning_architecture.png". "Apollo FSM" did not detect the "planning " module, but the "scenario" module. The "planning" module is initialized by the configuration file, but not "Apollo FSM". I found that the "planning" module used a planner that register a set of scenarios. And the scenarios manager uses "Apollo FSM" to detect the scene to run (by func ScenarioManager::ScenarioDispatch())?

**Comment by jmtao** [comment]
@daohu527 Currently, the "planners" are decided by conf file(we may switch to FSM later so that all the planners can be managed dynamically on the fly. It'll depend on what future planners we'll have) , and scenarios are managed by FSM.  
In this diagram,  Apollo FSM is outside of Planning Dispatcher module and provides FSM support.  It does not necessarily mean all the modules inside Planning have to use it.

**Comment by daohu527** [comment]
@jmtao Got it, thank you for your reply.
