### ISSUE TITLE
Cyber can monitor and evaluate the performance of each module

### ISSUE THREAD

**Issue by zyffei** [ApolloAuto/apollo#7968]
How can cyber monitor the scheduling and execution time of each module? Detecting the execution time of each task can meet the requirements? I found that by setting cyber_sched_perf=1, I can open the event log of task switching. Is there a visual tool available?

**Comment by zyffei** [comment]
If "cyber_sched_perf=1" is set, will it affect performance? How can we measure it? How can we measure the performance of each module task and arrange the scheduling strategy reasonably?

**Comment by zaxon** [comment]
hi, zyffei, i think there is 3 questions you ask here~ answers as follows:
1. questions about cyber_sched_perf
Answer:   perf event is developed for scheduler debugging, it record scheduler event like notify、swap_in、swap_out etc... it's not suitable for module proc time statistic, because module's proc function(it is croutine in cyber) may swap_in && swap_out several times, it is hard to organize these events together to calc module proc time.  finally, perf event certainly will affect performance(about 5%~10% E2E latency jitter), so we use it as offline debug tool when we meet framework performance issues
2. How can we measure the performance of each module task 
Answer: we have a E2E latency statistic && analysis tool for inner online use, but it's not suitable for all auto-drive products for now. we will have an internal discussion of this. i suggest u can try print logs in the proc start point && end point to statistic module proc time for debug purpose~ or transform a sensor time stamp from driver to control to make statistic of  E2E(end to end) latency for you to improve total performance && tail performance
3. arrange the scheduling strategy reasonably
Answer: we suggest developers use classic scheduler policy for common use or for the beginning. if u are already familiar with cyber, u can try choreo schedule policy to achieve higher performance, the advantage of choreo is its determinacy by binding related tasks to unique processor and given enough computing resource, the disadvantage of choreo is if we didn't binding tasks properly(total execute time of tasks in same processor exceed the period of sensor data related to them), we will gain a poor E2E performance. u can use choreo policy as follows:
a. tasks in auto-driving car organized as a DAG(Direct Acyclic Graph); 
b. the task in the critical path(most important path in DAG, modules like gnss、lidar driver、perception、planning、control etc.) should bind to same processor as possible for better cpu locality c. children node should have a higher priority than it's father node
d. total execute time of tasks in same processor won't  exceed the period of sensor data; 
e. we can arrange other tasks which is not in the critical path  into the processor pool  temporary;
f. we packaged linux sched confs into cyber sched conf, u can set linux sched policy && sched priority && pin cyber sched processor to proper cpus as u need.  u can set linux sched policy according to this article: https://drkp.net/papers/latency-socc14.pdf
you can access to cyber/conf/example_sched_choreography.conf && cyber/conf/example_sched_classic.conf for more details

**Comment by zyffei** [comment]
Thank you very much. Now we analyze the execution time of proc almost according to the method mentioned in Point 2. Is your tool measurement available in actual automatic driving? Do you need to modify cyber's code? Will it affect performance?

**Comment by zaxon** [comment]
> Thank you very much. Now we analyze the execution time of proc almost according to the method mentioned in Point 2. Is your tool measurement available in actual automatic driving? Do you need to modify cyber's code? Will it affect performance?

as metioned above, perf event in cyber is for offline debug purpose,  it can run in actual automatic driving, but i suggest turn off this tool if we run auto driving for mpi(online)~ "export cyber_sched_perf=1" in setup.bash if u need debug offline. the follow the output to analysis framework performance according to the enum follows:
enum class SchedPerf {
  SWAP_IN = 1,
  SWAP_OUT = 2,
  NOTIFY_IN = 3,
  NEXT_RT = 4,
  RT_CREATE = 5,
};

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
