### ISSUE TITLE
Cyber RT  croutine  problem

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#8213]
### System information

- **Linux Ubuntu 14.04**:
- **source **:
- **3.5)**:
Hello : 
    I have a question about  the number of thread and croutine, when I execute `bash scripts/perception.sh`，there is two processes which are mainboard(load module and execute) and cyber_launch,I use the commond that is “pstree -p  8222(mainboard‘s process number)”,
there are many threads, so I want to know when I start the module, How many threads will be started? How many coroutines? I see how many coroutines does each Reader create depending on the number of processors? 

Regard best. Thank  you.

**Comment by zhangchaoltt** [comment]
Hi, @breakisx according to your case, every perception process will create a timing wheel thread, an async log thread, a shm thread and 16 scheduling threads, other threads are from the detail alogrithm module, because the process does not have corresponding scheduler conf, so CyberRt scheduler uses the default_proc_num in cyber.pb.conf.  In addition, every reader creates one coroutine.

**Comment by anndymaktub** [comment]
@zhangchaoltt 
Dreamview do specify the scheduler conf.
https://github.com/ApolloAuto/apollo/blob/r3.5.0/modules/dreamview/backend/main.cc#L24
According to https://github.com/ApolloAuto/apollo/blob/r3.5.0/cyber/conf/dreamview_sched.conf
I think it should have 4  scheduling threads.

**Comment by zhangchaoltt** [comment]
@anndymaktub yes, it has 4 scheduling threads

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
