### ISSUE TITLE
Questions on traffic light module

### ISSUE THREAD

**Issue by krishnatoshniwal** [ApolloAuto/apollo#8286]
I had a few questions with the traffic light detection and recognition. 

1. What exactly does the quadrate traffic light mean [here](https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/camera/models/traffic_light_recognition), does it mean it has a protected left turn lane and the traffic light looks like this   
![4-channel-tl](https://user-images.githubusercontent.com/33788323/57599239-e6929680-750a-11e9-964b-84fc4ec49c89.png)

2. Does Apollo handle green or yellow arrow? Because [this](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/traffic_light.md) document says that there are 5 options for the traffic light and arrows is not one of them. 

3. How does apollo handle cases where there are more than three lights in the traffic light. For example  
![5-channel-tl](https://user-images.githubusercontent.com/33788323/57599366-46893d00-750b-11e9-8325-157a2a766569.png)

What changes would be needed in the traffic light module and the downstream modules to handle such cases?

**Comment by techoe** [comment]
When a traffic light has different shapes as shown above, the traffic light will be recognized purely by the color rather than location. Therefore, yes Apollo can recognize them. however, the probability of recognition will be lower and neighbor traffic lights will boost the confidence.

**Comment by krishnatoshniwal** [comment]
Thanks for the reply @techoe. I had noticed that all the traffic lights were being focused onto, even though each lane had its own traffic light. So I had the question, Apollo doesn't choose just one traffic light according to the lane the ego vehicle is in, instead it focuses on all  the traffic lights in that direction, does it?

**Comment by techoe** [comment]
Correct. When self-driving car (SDV) is going thru an intersection, all
traffic lights in the HDmap were detected and recognized. After majority
voting, the final traffic light of the intersection is determined.

**Comment by krishnatoshniwal** [comment]
Got it, thanks! The traffic lights for left turn signal are not differentiated from the other traffic lights at the moment?

**Comment by boyang9602** [comment]
Hi, 
I have the same question about the `quadrate` traffic light. What kind of traffic light does it mean exactly? [As the code shows](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L337), it is detected by the deep learning model in the traffic light detection step. You have an enumerate type
```
enum class TLDetectionClass {
  TL_UNKNOWN_CLASS = -1,
  TL_VERTICAL_CLASS = 0,
  TL_QUADRATE_CLASS = 1,
  TL_HORIZONTAL_CLASS = 2
};
```
Since this step is just detecting the bounding boxes of the traffic light, I think these enumerated types means the layout of the traffic lights. 
So in my opinion, I feel that VERTICAL means 
![image](https://user-images.githubusercontent.com/30889920/154525150-c521e865-546d-477c-9e9e-3545249bf23c.png)
HORIZONTAL means
![image](https://user-images.githubusercontent.com/30889920/154525603-17746121-4866-4e8f-b802-7fbf98eae771.png)
And QUADRATE probably means a single light, like 
![image](https://user-images.githubusercontent.com/30889920/154525961-ef198725-be3f-4740-a57c-01ba89829b9e.png)

Is my understanding correct?

Is this a case you are going to handle?
![image](https://user-images.githubusercontent.com/30889920/154526244-8aec6409-f63a-4b63-a8e0-fbf38a73a3b3.png)
If so, what type of this one should be? 
In the detection (I'm using Apollo v5.5.0), the scores are 
```
I0215 23:08:37.515722 22558 detection.cc:323] []result_data 0.437532  # UNKNOWN
I0215 23:08:37.515745 22558 detection.cc:323] []result_data 0.559215  # VERTICAL
I0215 23:08:37.515763 22558 detection.cc:323] []result_data 0.000870899  # QUADRATE
I0215 23:08:37.515781 22558 detection.cc:323] []result_data 0.00238272  # HORIZONTAL
```

Thanks!
