### ISSUE TITLE
Trouble on Launching Planning Module

### ISSUE THREAD

**Issue by yoyouwen** [ApolloAuto/apollo#8456]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**:Source
- **Apollo version (1.0, 1.5,  2.0, 2.5, 3.0)**:3.5

### Steps to reproduce the issue:
I am trying to use Sim_Control according to the guide but I failed to launch the planning module on dreamview UI. I turned the planning module on but after I sent a route request the planning module turned off automatically. 

![image](https://user-images.githubusercontent.com/43387865/58193529-c9717b00-7cf5-11e9-93da-ab500e3ab3fd.png)

Then I try to launch the planning module manually using cyber_launch start  launch/planning.launch after I send a new route request. And I got the following log:
![image](https://user-images.githubusercontent.com/43387865/58195953-c4afc580-7cfb-11e9-89eb-4550a0fc590f.png)

**Comment by latolium** [comment]
I've got exactly the same issue, driving me crazy.

**Comment by yoyouwen** [comment]
> I've got exactly the same issue, driving me crazy.

Do you figure out a way to solve this? I am still very confused.

**Comment by latolium** [comment]
> > I've got exactly the same issue, driving me crazy.
> 
> Do you figure out a way to solve this? I am still very confused.

No I even did a clean OS install, clean pull everything but I still the same error.

**Comment by jmtao** [comment]
@yoyouwen if you want to launch planning module from terminal, you can turn off planning module from DreamView, and then launch planning manually from terminal as what you did in the screenshot you posted. 
And, you need launch planning mode first, and then send routing request.  So that planning module can receive routing response.  Otherwise, when you planning module starts, the routing response was already gone.  Although you can see routing red line in DreamView, the planning module actually never got it in time. 

Let us know if that's the case.

**Comment by jmtao** [comment]
Hi @yoyouwen, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
