### ISSUE TITLE
Why removed side_pass scenario ?. Has it been merged to other scenarios?

### ISSUE THREAD

**Issue by hongbozhu0303** [ApolloAuto/apollo#8885]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by hongbozhu0303** [comment]
@natashadsouza , Hi Natasha,  Thanks for tagging my question. It looks like the side pass has been merged to lane follow scenario. Just curious what the reason for this change.

**Comment by panjiacheng** [comment]
Hi @hongbozhu0303 ,
Thanks for the question. We'd hope that side-pass of any static/low-speed obstacle can be a "infrastructure-ish" functionality rather than a stand-alone and exclusive scenario. Now the side-pass feature is incorporated as part of the path-bounds decider task. You can choose to turn it on or off by properly configuring the path-lane-borrow decider task.
Therefore, it is not an accurate description to say that side-pass is merged into lane-follow; rather, side-pass is merged into almost all the other scenarios, including but not limited to: traffic lights, stop signs, etc. Whether side-pass is turned on or off is contingent upon your specific needs. For example, if you want the vehicle to be agile, then turn side-pass on for all scenarios; if you feel it not safe to side-pass in intersections, then turn it off for those related scenarios.
Hope that adequately answers your question. Thanks.

**Comment by hongbozhu0303** [comment]
Hi @panjiacheng , 
That makes perfect sense. Really appreciate your help.
