### ISSUE TITLE
Dynamics equation change using lateral controller in reverse

### ISSUE THREAD

**Issue by renegadephysicist** [ApolloAuto/apollo#9229]
In [lat_controller.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/control/controller/lat_controller.cc#L375) when in reverse mode the `matrix_a_coeff_(0, 2)`  is given a non zero value and `matrix_a_coeff_(0, 1)`  a zero value. 

Matrix_a is top matrix in this equation from Rajamani: 
![image](https://user-images.githubusercontent.com/32599092/61812896-60fd6200-ae3c-11e9-8b2b-60748959b281.png)

where:
![image](https://user-images.githubusercontent.com/32599092/61812494-8342b000-ae3b-11e9-8ad6-d76a52a92bab.png)

The two numbers highlighted in red are swapped when in reverse mode.

This would result in the change in lateral error equal to the heading error. I don't understand why `matrix_a_coeff_(0, 2)`  is non-zero in reverse mode.

**Comment by kevin-y-wang** [comment]
In the reverse-driving model, due to the inaccuracy of the lateral translational motion which was originally designed for forward driving, we replace this dynamic equation with the following kinematic equation:
y_dot  = V * sin(phi-phi_des)
by simplification and small-angle assumption, it is given by:
e1_dot = V * e2
Thus, we have 
matrix_a_coeff_(0, 2) = 1  (when gear_reverse)
matrix_a_(0, 2) = matrix_a_coeff_(0, 2) * v  (when gear_reverse)

**Comment by renegadephysicist** [comment]
Thanks for the reply, would it not be more accurate to use the same kinematic model with rear wheel steering and the heading rotated 180 degrees?

**Comment by kevin-y-wang** [comment]
Based on our design principle, the autonomous driving car is assumed to be the front-wheel steering which may cover most of the car models in market. 
However, if the car in your project happened to be a rear-wheel steering car, then directly applying the forward-driving dynamics (with some variables changed by 180 degrees) will be a good fit. Thanks.
