### ISSUE TITLE
What format is GPS data?

### ISSUE THREAD

**Issue by RbRioja** [ApolloAuto/apollo#923]
I am reading the testdata gps data example:
localization {
  position {
    x: 357.51331791372041
    y: 96.165912376788725
    z: -31.983237908221781
But I can not understand what format these numbers are in. They cannot be latitude/longitude as latitude needs to be between -90 and 90. They cannot be UTM because we would need the zone number. Can someone tell me what format this is? Also how can we convert latitude and longitude to this format?
Thank You :)

**Comment by Capri2014** [comment]
@RbRioja Hi RbRioja, it is UTM, which is defined in different launch files in "https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/gnss/launch/"

As of the testdata collected, since it is in Sunnyvale, CA, we use 
 "  <arg name="proj4_text" default="+proj=utm +zone=10 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs " />"
