### ISSUE TITLE
CyberRT, coroutine to thread mapping 

### ISSUE THREAD

**Issue by gusamqq** [ApolloAuto/apollo#9433]
As I understand, the mapping from tasks (coroutines) to thread is dynamic at runtime, not static at design time. But this may create problems in timing predictability, since it is difficult or impossible to determine a thread's WCET (worst-case execution time) for real-time schedulability analysis, since you do not know which tasks will be executed in the thread. 
Where can I find more details on the task-to-thread mapping algorithm?

**Comment by gusamqq** [comment]
What is the RTOS (real-time operating system) used underneath CyberRT? Is it developed in-house?

**Comment by wutianze** [comment]
Same question, I find that cyber RT uses qos in RTPS to maintain communication's qos. But I cannot find RTOS in cyber. Maybe in Apollo kernel? Does Apollo build a customized linux kernel?

**Comment by yiakwy** [comment]
@wutianze @gusamqq @quning18 There is RT Linux, i.e, with RT patch. you can compile Linux to real time one, so that you can create thread with specified priority, stack size and that which will not be interrupted by other threads.

This is done in "SetSchedPolicy"
> https://github.com/yiakwy-mapping-team/cybertron/blob/master/modules/scheduler/common/pin_thread.cc

The file also includes "sched.h" for allocating RT thread and task. Also see apollo-kernel : the default RT OS is Linux with RT patch.

In cybertron, if I understand right, they are physical thread. The project instead uses user - space thread (see brpc by Ge jun) to allocating tasks in user space.

Wish my answer settle down your question.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
