### ISSUE TITLE
overtake behavior in public_road_planner

### ISSUE THREAD

**Issue by stdpython** [ApolloAuto/apollo#9749]
hello, I wonder how to overtake the veh in front of the ego-car, I know that overtake behavior made by the speed_decider, and search or optimize in S_T diagram, but I found that there is not "Lateral info", and it does not make sense,  is there anybody help me out?
Thank you!

**Comment by jmtao** [comment]
@stdpython I don't quite understand what you meant by "there's no lateral into and it doesn't make sense".  I can briefly explain what OVERTAKE decision means.  OVERTAKE / YIELD are longitudinal speed decisions. When a moving object's path may cross ego-car's, we make OVERTAKE / YIELD decisions based on ST-graph. 
**OVERTAKE** means we'd plan ego-vehicle to arrive at the path crossing point (or equivalent s value of the path crossing point), **BEFORE** the moving obstacle. 
**YIELD** means we'd plan ego-vehicle to  arrive at the path crossing point (or equivalent s value of the path crossing point), **AFTER** the moving obstacle. 
These are the "longitudinal speed" decisions.
Let us know if this help answer your questions.  Thanks.

**Comment by jmtao** [comment]
@stdpython we call this SIDEPASS. we only side pass static obstacles. Since they are static, we block the area occupied by these static obstacles when we plan the path. So that we can NUDGE (in lane) them or SidePass them (across lane) as appropriate. 
We don't side pass moving obstacles even if they are slow.  First of all, they have road right since they are ahead of us; secondly, it's hard to predict if they are going to speed up soon. That may cause failure in our future planning.  Safety is till among the top priorities of our consideration.

**Comment by stdpython** [comment]
OK, I understand the decision design, thank you.
